### ISSUE TITLE
Limit users from certain sources to only be able to log in on certain tenants

### ISSUE THREAD

**Issue by unixfy** [goauthentik/authentik#1005]
**Is your feature request related to a problem? Please describe.**

Currently, all users stored in authentik can log in through any tenant. However, some admins (myself included) might want to limit users from a certain source or in a certain group to only be able to log in through one tenant. For instance, I might want users originating from my internal LDAP to only be able to log in on my "internal" tenant, while other users should only be able to log in on my "default" tenant. This resembles the functionality of Keycloak's Realms.

**Describe the solution you'd like**

There should be a configuration option in the sources and/or tenants UI(s) that allow admins to select which user sources or groups can log in through which tenants.

**Describe alternatives you've considered**

The only real alternative to this is to set up additional authentik installations for specific tenants, but this adds extra maintenance overhead.

**Comment by BeryJu** [comment]
So you can currently select which sources should be shown in the Identification stage, but I assume you mean if userA logs into tenantB they get redirected to tenantA?

**Comment by unixfy** [comment]
Changing sources in the identification stage doesn't seem to actually change anything for me. What I would like to see is the option to make it so that if userA tries to log into tenantB, it will act as if that user didn't exist (but if userA tries to log into tenantA, it will work fine).

**Comment by BeryJu** [comment]
I purposefully added tenancy as "soft-tenancy", as with the current design, this can't be done easily.

In the backend, all users end up in a single pool, regardless of which source.

You could implement this with an Expression policy on the flow, and check any user attribute you want, but I don't think theres a good way to implement this as a general setting, especially since a user can "belong" to multiple sources.

**Comment by unixfy** [comment]
> You could implement this with an Expression policy on the flow, and check any user attribute you want, but I don't think theres a good way to implement this as a general setting, especially since a user can "belong" to multiple sources.

I guess one way I could do this (at least for my use case) is to check users based on which OU they are in... would it be possible to validate this through expression policies?

**Comment by BeryJu** [comment]
Yeah you can just check users.attributes["distinguishedName"], so

```python
return request.user.attributes.get("distinguishedName", "").endswith("foobar")
```

After some more thought, it could in theory be done to have a list of source that are allowed for a tenant, since currently all Web-based sources create a Connection model in the database (just LDAP doesn't).

However even with that, it wouldn't be possible to match by OU, so you'd still have to write an Expression policy for that.
