### ISSUE TITLE
stable docker tag

### ISSUE THREAD

**Issue by eglia** [goauthentik/authentik#1023]
**Is your feature request related to a problem? Please describe.**
Currently there is only a "latest" docker tag, which includes pre-releases. In a previous release it was even the case that the latest tag went something like 2021.4 -> 2021.5-RC1 -> 2021.4.1.

**Describe the solution you'd like**
It would be nice to have a separate tag for stable versions.

**Describe alternatives you've considered**
The "proper" way would probably be to not use the latest tag and get a specific version, but this would require additional maintenance work to check what the latest version is and update the docker-compose file.

**Additional context**

**Comment by BeryJu** [comment]
While I do agree that a stable tag would make sense, I'm not quite sure how to automate the creation (since in the GitHub actions pipeline, I can't easily check if its a pre-release or a normal release), but also it might sense to only push to :stable by hand, perhaps as an additional way to test new releases.

**Comment by caraar12345** [comment]
Perhaps you could do a simple string check (if the second and third to last characters are 'rc', then it's not stable)?
