### ISSUE TITLE
Setting up paperless on LXC container. 

### ISSUE THREAD

**Issue by TDX44** [goauthentik/authentik#10401]
I was attempting to setup Authentik with paperless but my paperless install is from ttek on an LXC container. There were instructions on the authentik documentation stating to add the following to the docker-compose.yaml file but...

```dockerfile
PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
    {
      "openid_connect": {
        "APPS": [
          {
            "provider_id": "authentik",
            "name": "Authentik",
            "client_id": "< Client ID >",
            "secret": "< Client Secret >",
            "settings": {
              "server_url": "https://authentik.company/application/o/paperless/.well-known/openid-configuration"
            }
          }
        ],
        "OAUTH_PKCE_ENABLED": "True"
      }
    }
``` 

there are no instructions on adding the variables to a bare metal paperless install. Has anyone successfully done this? If so, would you mind explaining  where to add the variables?

Paperless v2.10.2
Authentik v2024.4.2

**Comment by Goblinmine** [comment]
I also struggled with this one for a bit.

You need to add this configuration to the paperless.conf file. If you used the ttek script, the file should be located at `/opt/paperless/paperless.conf`. The first difference to note is that it uses equal signs for key-value pairs instead of colons. Additionally, since this file does not support multiline values, you need to convert the JSON into a single line.

The rest is the same as in the Authentik documentation.

Values to replace are
`< Client ID >`
`< Client Secret >`
`authentik.company`

```
PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect
PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect":{"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"authentik","name":"Authentik","client_id":"< Client ID >","secret":< Client Secret >","settings":{"server_url":"https://authentik.company/application/o/paperless/.well-known/openid-configuration"}}]}}
```

**Comment by TDX44** [comment]
Thanks, I'll give this a try today.

**Comment by TDX44** [comment]
Worked flawlessly, thanks!
