### ISSUE TITLE
how to setup device code flow for a symbolserver in order to debug in linux environments

### ISSUE THREAD

**Issue by RainerMuehlberger** [goauthentik/authentik#11353]
Hello,
We want to introduce a symbolserver (debuginfod) for linux based development and set up the following infrastructure (see the attachment). We use traefik as a reverse-proxy and authentik as a authentication provider. We have to use Azure AD for authorization as well. We want to upload debug symbols with curl or Azure DevOps Pipelines and want to debug with gnu debugger gdb.

How do we have to setup the authentik flow for that (device code flow) use case and configure authentik in a proper way? Is it possible to give us a guideline how to achieve it? Is the Azure AD integration possible in this use case? 

Screenshot with the current infrastructure:
![Screenshot 2024-09-12 141319](https://github.com/user-attachments/assets/3a5b503c-8de8-4bc6-8dae-a6bc8533024c)

Thank you very much for your help.

Greetings,
Rainer

**Comment by RainerMuehlberger** [comment]
seems not an easy question, right?

**Comment by BeryJu** [comment]
Since debuginfod does not seem to support any kind of native OIDC, I'm assuming this would be setup with forward authentication/the proxy provider. Our proxy provider does not work with the device code flow, as it does not have a way to the show the Code the user has to enter, especially when used with APIs or other protocols.

We'll be working on some related features that will make this possible in the future, we'll track development of the feature making this possible in #11955

**Comment by RainerMuehlberger** [comment]
thank you very much for the feedback.
