### ISSUE TITLE
Slow LDAP connection making authentik unresponsive

### ISSUE THREAD

**Issue by davidus05** [goauthentik/authentik#1764]
**Describe the bug**
When having an active LDAP source and some user authenticating against it, everything works fine. But when the external LDAP server is not responding (or responding slow), authentik gets unresponsive and "stuck", which leads in a "Bad Gateway" error in the end, which can only be solved by restarting the container. No other tasks can be performed in the meantime.

**To Reproduce**
1. Add external LDAP source
2. Verify that authenticating with an LDAP user works
3. Interrupt connection between authentik and the LDAP server (firewall restriction, turn LDAP server off)
4. You should see an infinite loading screen, while authentik not responding

**Expected behavior**
authentik should be usable while waiting for the result of the LDAP server (do that job async or implement some timeout?). The best solution would be an async solution together with some configurable timeout setting (in seconds).

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.10.3
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
now that builds are (somewhat) working again, could you test the beta with your setup? @davidus05

**Comment by davidus05** [comment]
Hey! Thanks for the fix. I'll give it a try tomorrow and keep you updated.

**Comment by davidus05** [comment]
Just here to confirm — works great, after 15 seconds authentik is usable again if there is some timeout! Additionally, would be there some async solution that such timeout is not "blocking" everything else for 15 seconds and making authentik unresponsive?

**Comment by BeryJu** [comment]
I wish there was an easy way, but due to the way django WSGI and rest_framework function, this has to be synchronous and can be, depending on the amount of requests, indeed a bottle neck.

Allthough keep in mind, this kind of password checking is only done when
- The user has no password set yet (freshly sync'd)
- The LDAP Sync resets their password (when it was changed in LDAP)

So for most normal logins, it shouldn't be too much of an issue.
