### ISSUE TITLE
User can't confirm account to different browser

### ISSUE THREAD

**Issue by Bhautik0110** [goauthentik/authentik#1801]
**Describe your question/**
I had created a signup flow with email verification, whenever user signup, It sends an email and the user can confirm the email, the account is activated. If I open email confirmation link in the same browser, the flow works correctly, But when I open the confirmation link in a different browser It restarts the signup flow, the user account is still inactive.

I also tried by entering the same email, and password entered in confirmation. It shows `Request has been denied`. 

**Relevant infos**
i.e. Version of other software you're using, specifics of your setup

**Screenshots**
Whenever a user opens the confirmation link in a different browser. It restarts flow from the beginning.
![image](https://user-images.githubusercontent.com/76986554/141925552-0f9e10f7-7c57-4678-9e81-f12080777fcf.png)

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2021.8.5]
 - docker-compose

**Comment by BeryJu** [comment]
This is caused by the way the FlowExecutor works, contextual data is stored in the user's session, which will be different on another browser. In the same browser, the flow will continue with the email stage, which will be passed the token and then continue.

In a fresh session, the token is passed, but because its a new session, the flow starts from the beginning.

While I could just add a hook to all stages to allow them to react to this on flow start, I would also need to save the current flow context into the token, so the user can continue.

**Comment by BeryJu** [comment]
The token currently isn't, its just a random string of characters. I also dont think a JWT makes sense here, as the flow context might contain sensitive data, which shouldn't be shown to the user.

The data would have to be saved serverside somewhere, it would make sense to save it in the Token object but I'm also not really a fan of that

**Comment by deltasquare4** [comment]
> it would make sense to save it in the Token object but I'm also not really a fan of that

Is the token associated with flow id somehow? The flow can be changed to expect a session at the verification state, and when not found, the user could be redirected back to login page instead of starting the flow from the beginning. I am not intimately familiar with the codebase to know whether this is feasible.

**Comment by BeryJu** [comment]
The flow is only associated with the user that's currently pending in the flow (whether newly created or logging in).

The issue with redirecting back is that for enrollment flows, the user would have to enter all of their information again

**Comment by rizwan95** [comment]
So, how do we solve this problem? It is a major show stopper if it is not solved.
