### ISSUE TITLE
Enable/Disable Applications

### ISSUE THREAD

**Issue by guyguy333** [goauthentik/authentik#1837]
**Is your feature request related to a problem? Please describe.**

I would like to be able to disable or enable again an Application. Disabled application means app is no longer listed in User interface.

**Describe the solution you'd like**

A checkbox in app configuration to enable/disable app but also a read only checkbox in applications list to see easily what app is enabled or disabled.

**Describe alternatives you've considered**

Delete application

**Additional context**

**Comment by BeryJu** [comment]
with https://github.com/goauthentik/authentik/commit/8794c840cfdb9c7062a9f564f43aae4420ce4f50 and https://github.com/goauthentik/authentik/commit/6ed7d842e4b5d77bb0095ecaecd1b9e4b54df190 you can just set the launch URL to something not starting with http and it'll be hidden

**Comment by hmans** [comment]
I'm a little frustrated that this issue was closed as completed with the "workaround" mentioned above. Hiding an application from the list of apps is absolutely not the same as disabling it.

Temporarily disabling an entire application would be a very nice feature to have. At the moment, the only way to temporarily disable an application is to modify its policy configuration (eg. setting its policy engine to `ALL` and adding a "always deny" policy that always fails, or similar hacks.)

**Comment by sebastianlau** [comment]
The docs were updated https://docs.goauthentik.io/docs/add-secure-apps/applications/manage_apps

Set the launch URL to "blank://blank" to hide it (yes, that's still not disabled and annoying if you want to persist an actual launch url till later)

I've posted this here as it was the first page to come up in google when I searched for "authentik disable application"

**Comment by Healzangels** [comment]
Attempting to disable/hide an application as well and also came across the same doc.

Similar results setting the Launch URL to blank://blank still keeps the application present on the user interface. 

Curious if anyone had another solution/if there were new recommendations. Thanks!

**Comment by Kruemmelspalter** [comment]
Another way to do this is creating a policy and setting the client ip to 0.0.0.0 and then binding the application to said policy
