### ISSUE TITLE
LDAP Provider is very slow

### ISSUE THREAD

**Issue by dstengele** [goauthentik/authentik#1946]
**Describe your question/**
I am trying to replace OpenLDAP with the Authentik LDAP Provider, but I am facing the problem that all authentication requests take multiple seconds to complete. This is especially noticable when trying to use it for authentication in Dovecot. Each authentication takes about 4-5 seconds to complete, which makes IMAP nearly unusable. The problem also manifests itself with SOGo where the login takes very long.

Am I doing something wrong?

**Relevant infos**
Dovecot 2.3

**Version and Deployment (please complete the following information):**
 - authentik version: 2021.12.1
 - Deployment: docker-compose

**Additional context**

**Comment by eglia** [comment]
The LDAP lookups are very slow for me too. For dovecot, I solved the problem by enabling the auth cache (set `auth_cache_size` to a suitable value in dovecot.cf, see [here](https://wiki2.dovecot.org/Authentication/Caching)).

**Comment by BeryJu** [comment]
The actual lookups shouldnt be too slow when using the cached searcher (configurable in the provder), but binds currently do take a couple seconds. This is because the LDAP Bind uses a Flow in the background, so you'll be doing at least 2 HTTP requests to the core authentik server on bind.

I do want to add another option to use the session duration for LDAP binds, so that only the first bind takes longer and then later binds are authenticated using the session from the first bind.

**Comment by dstengele** [comment]
This is still happening.

**Comment by Shyru** [comment]
We also experience this issue. Most of the times LDAP binds take around 2 seconds to complete (which is tolerable), but sometimes it takes more than 20 seconds. We already have auth caching enabled for the provider. So with the mentioned pull-request above, is this issue considered as fixed, or are there still any improvements planned?

**Comment by BeryJu** [comment]
We'll do some optimisation on the /api/v3/core/users/ endpoint which is the main culprit for the slower response times here in the next release. Thanks for reporting this!
