### ISSUE TITLE
Iframe/embedding/Content Policy Proxy authed application.

### ISSUE THREAD

**Issue by matt1309** [goauthentik/authentik#1998]
I'm aiming to embed several of my applications into a central website (nextcloud). The aim being once logged in using authentik sso all my apps will be accessible within nextcloud (using external sites plugin). 
This nextcloud plugin works by using iframes to embed the applications into nextcloud pages. 

I've noticed that for my "Forward Auth" authenticated services this does not work. I get a message noting that auth.company (authentik domain) cannot be embedded and i would need to adjust header x-frame-options (or i believe the better option is setting content policy now). 

eg adding x-frame-options allow-from https://nextcloud.domain. 

How do i do this? I'm not sure if this options is built into Authentic and I'm just not spotting it or if this is a feature i should maybe be requesting. 

**Relevant infos**
Latest version (installed this week)

**Screenshots**
No use

**Logs**
I see no logs/notifications for this in authentik (again i might just be looking in the wrong place, please tell me if that's the case)

**Comment by matt1309** [comment]
I think I've found the option in the code. Within authentik/root/settings.py line 261 

"django.middleware.clickjacking.XFrameOptionsMiddleware",

I believe this sets xframe options to deny by default. I think changing this will update the options and allow embedding however does open up potential clickerjacking issues. Maybe i can add customer headers to outpost?

Anyone have any suggestions

**Comment by BeryJu** [comment]
I'm not sure this is something that should be configurable in authentik itself, I would probably be easier to overwrite/remove that header in your reverse proxy

**Comment by matt1309** [comment]
Great idea! Thank you!!

**Comment by Healzangels** [comment]
Hey sorry to post on just an old thread but trying to setup something very similar. I've added proxy_hide_header X-Frame-Options; to the reverse proxy of my auth site.

This gets me to see the auth page within my iframe however I go into an endless loop with the auth loading screen.

Again sorry for posting on an old closed post but thought maybe since you'd been working on this had better luck/an idea for a fix. Thanks!

**Comment by matt1309** [comment]
> Hey sorry to post on just an old thread but trying to setup something very similar. I've added proxy_hide_header X-Frame-Options; to the reverse proxy of my auth site.
> 
> This gets me to see the auth page within my iframe however I go into an endless loop with the auth loading screen.
> 
> Again sorry for posting on an old closed post but thought maybe since you'd been working on this had better luck/an idea for a fix. Thanks!

I'll take a look tonight and share my nginx conf

**Comment by matt1309** [comment]
Replace the stuff starting with *** with your specific details. 

```
location / {
        proxy_pass https://***AUTHENTIK_URL:9443;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # This needs to be set inside the location block, very important.
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_hide_header X-Frame-Options;
        add_header X-Frame-Options "ALLOW-FROM https://***MYDOMAIN.COM/";
```

**Comment by Healzangels** [comment]
Awesome, thanks so much for sharing and the super quick response to a years old thread. 

Look forward to giving it a test after work, thanks again!

**Comment by Healzangels** [comment]
Was able to play around with this a bit and unfortunately hitting a bit of a wall. 

Maybe if I describe my setup can shed some light on where I am going wrong. Also no worries if unable to assist, a bit over my head with the setup so learning as we go.

I currently have authenik setup on port 9000 (believe the default) and have two different setup currently so unsure if one will work with the above and the other not so much.

I'm using NPM as my reverse proxy. For my arr services that I'd like to have the iframe ability on I currently have setup within authentik as the reverse proxy rather than just using it for forward auth to NPM.

For these I have it set this way to also pass local credits for local auth as well. Within NPM my destination is set to by my authetikaddress:9000

My other services which I don't have setup as a reverse proxy but as a forward auth I then have with the advanced setting the block of code from authetik for NPM setups. Both setup's work and auth into my sites.

I guess this then where my questions really begin. 

For the block of code above would I be placing this within my NPM reverse proxy for http://auth.myserver.com? (Or into the block of code provided by authetik or NPM in the advanced setting of the site?) 

Placing `proxy_hide_header X-Frame-Options;` line into the / location for my auth.myserver.com site which I'm using for reverse proxy got me as far as seeing the authentik login page in the iframe. This is where I attempted to add the above but had questions for. Also not sure what I've setup works with that since it specifies an address with the bottom line?

Apologizes for the wall of text as well and over the top troubleshooting ask, no worries if unable to assist and again thanks for providing the above!

**Comment by matt1309** [comment]
I'm using very old version of authentik and just basic nginx install, I've pretty much not updated since this post so things may have changed but here's my setup:

Under auth.domain.com: agian change anything with *** infront of it. 

`location / {
        proxy_pass https://***AUTHENTIK_IP:9443;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # This needs to be set inside the location block, very important.
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_hide_header X-Frame-Options;
        add_header X-Frame-Options "ALLOW-FROM https://***domain.com/";


    }`

Then on the page page I want as an iframe (this page is written in php so just using nginx as webserver not reverse proxy but I've highlghted where reverse proxy would go shouldn't impact the authentik parts.)

`location / {
    # Put your proxy_pass to your application here


#authentik-specific config
     auth_request        /akprox/auth/nginx;
    error_page          401 = @akprox_signin;

 # translate headers from the outposts back to the actual upstream
     auth_request_set $authentik_username $upstream_http_x_authentik_username;
     auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
     auth_request_set $authentik_email $upstream_http_x_authentik_email;
     auth_request_set $authentik_name $upstream_http_x_authentik_name;
     auth_request_set $authentik_uid $upstream_http_x_authentik_uid;

     proxy_set_header X-authentik-username $authentik_username;
     proxy_set_header X-authentik-groups $authentik_groups;
     proxy_set_header X-authentik-email $authentik_email;
     proxy_set_header X-authentik-name $authentik_name;
     proxy_set_header X-authentik-uid $authentik_uid;
 }


# all requests to /akprox must be accessible without authentication
location /akprox {
    proxy_pass          http://***AUTHENTIK_IP:9000/akprox;
    # ensure the host of this vserver matches your external URL you've configured
    # in authentik
    proxy_set_header    Host $host;
    add_header          Set-Cookie $auth_cookie;
    auth_request_set    $auth_cookie $upstream_http_set_cookie;
}

# Special location for when the /auth endpoint returns a 401,
# redirect to the /start URL which initiates SSO
location @akprox_signin {
    internal;
    add_header Set-Cookie $auth_cookie;
    return 302 /akprox/start?rd=$request_uri;
}

}`

**Comment by Healzangels** [comment]
Dang I feel like I'm nearly there. Was able to I believe understand + piece things together however getting an online status from NPM when I enter the full location / block.

Thanks so much for going above and beyond with code snippets/explanation. I'll be prodding along but may be out of my depth a bit. Idk if you'd ever consider a beer and pizza (or similar) for some time troubleshooting xD.

Thanks again.
