### ISSUE TITLE
LDAP Sync No Membership

### ISSUE THREAD

**Issue by KuLi** [goauthentik/authentik#2392]
**Describe your question/**
LDAP syncs user and groups but groups are empty

**Relevant infos**
UCS Univention

**Screenshots**
![image](https://user-images.githubusercontent.com/345592/155747610-c6377532-76fa-4d5d-a9af-5f615203e355.png)

**Logs**
ldap_sync_ucs-01_user
    Last sync: 2/25/2022, 5:00:05 PM
    Synced 86 objects.

ldap_sync_ucs-01_group
    Last sync: 2/25/2022, 5:00:05 PM
    Synced 30 objects.

ldap_sync_ucs-01_membership
    Last sync: 2/25/2022, 5:00:02 PM
    Synced 30 objects.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.1.5
 - Deployment: docker-compose

**Comment by e36Alex** [comment]
Nobody an idea to this topic?

**Comment by xpufx** [comment]
This issue cannot be diagnosed without seeing your group schema in LDAP.  @KuLi does your group have a parameter called 'cn' ? @e36Alex does yours have 'entryUUID' ?   Make sure you understand that the single "Object uniqueness field" identifier applies  to both Users and Groups. Both have to have the same field which is not true by default on every openldap implementation. I was using 'cn' for groups and 'uid' for users myself and had to add a 'uid' parameter to my group too. If you end up having to add the parameter like I did and cannot because of schema constraints, look into ldap "extensibleObject". 

Finally. User and Group containers should probably have separate uniquness fields in authentik.

**Comment by e36Alex** [comment]
Hi and thanks for your reply!

My group schema in ldap is acutally quite simple because i just did first steps with ldap:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/26880334/159137079-d69346b8-78e5-4c4c-9d95-d2dc4994041c.png">

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/26880334/159137131-0ae0b6f6-1b6e-4fa8-a72d-47ab8a708f2f.png">

I got a entryUUID:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/26880334/159137164-741c6c31-1721-4241-a15f-1a43e8f2f96c.png">

And configured it as unique object field (same field for users and groups):
<img width="436" alt="image" src="https://user-images.githubusercontent.com/26880334/159137197-1926a88f-8469-4f87-81ab-ccd012860a87.png">

**Comment by xpufx** [comment]
If I am not mistaken entryUUID is an internal attribute. Authentik's ldap sync code might not be retrieving those. 

Here's what  my working config looks like for comparison.

![dom](https://user-images.githubusercontent.com/25581961/159137505-6c61882c-3639-4ae1-8974-ad7da5f26f41.png)

**Comment by e36Alex** [comment]
You are right, the uuid is listed at internal attributes.
Can i somehow check, if authentik is receiving this field?

Would your solution mean, i had to add an "manual" unique attribute to all users and groups?

**Comment by xpufx** [comment]
You probably already have a unique field for your users. You actually have one for your groups too (cn). The problem is authentik wants one field name and wants to use it for both user and group. So in my case since my RID field for users was 'uid' it was a quick fix to add the 'uid' field to groups too. This was authentik was satisfied using 'uid'.  

If you and I were using 'cn' for both like we're supposed to, everything would be fine by default. :)

**Comment by e36Alex** [comment]
Thank you! 
I cant remember why i switched from default config.
This now works partly.

Only problem now is, that only the first memberuid of a group is added to the group. Other members dont get added.

**Comment by e36Alex** [comment]
Maybe its something wrong with my ldap?

When i check the users / groups the i stuck at this:

MemberUIDs at group are correct:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/26880334/159138940-5508224e-b8ed-490a-af77-8356b3061f2a.png">

Looking at the users, the is just one entry:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/26880334/159138960-0dc76330-39a3-4af4-9295-bf5b1a94b9a8.png">

<img width="587" alt="image" src="https://user-images.githubusercontent.com/26880334/159138969-da63474a-248b-47ed-9d86-f8f2d8ba7690.png">

**Comment by xpufx** [comment]
If you're not in production yet it might be best to delete all users and groups and do a clean sync.

**Comment by e36Alex** [comment]
Actually i am not really in production, yet. I deleted the users and groups in authentik several times, yet.

I deleted the last posts because i found out, that there is something wrong at my ldap. But still its just running partly.

1. I deleted all my users and groups from ldap and then synced the ldap again in authentik --> none of the users/group were deleted at authentik
2. So i deleted all users/groups manually in authentik
3. I recreated the users and groups again in ldap - but i still got the problem, that sometimes the users are added correctly and sometimes not. Also changes (edit or delete) at a user dont get synced from ldap to authentik

I am not sure, if the memberuids are the full DN - how can i check this?

**Comment by xpufx** [comment]
There's a known limitation as listed here #1644 . Currently sync operations do not remove users from authentik. 

I don't want to lead you to the wrong path regarding memberuids being full DNs. Mine are. But maybe phpldapadmin represents them like that and it still works?.  

You're also having issues with users? Not just groups?

**Comment by e36Alex** [comment]
Thanks for your help and patience.

After a few more tries and changes of the uid betweed entryUUID and CN it seems to work now with CN while adding new users and groups.
Removing users and groups in any way from ldap does not change anything at authentik.
Only if i first remove a user from a group and sync the change immediatly, the user gets removed from group in authentik.
If i remove the user from the group and then delete the user in ldap the user does not get removed from group in ldap.
