### ISSUE TITLE
Flow context issue

### ISSUE THREAD

**Issue by BramBeeyond** [goauthentik/authentik#2458]
**Describe the bug**
While running a user unenrollment flow as userA I'm trying to unenroll userB. I run into some issues with my expression policy which seems to be caused by an issue with the current context. I put my flow configuration, policy and contexts in the pdf below.

**Additional context**
See here the full report.
[bug_report_authentik (1).pdf](https://github.com/goauthentik/authentik/files/8215344/bug_report_authentik.1.pdf)

**Comment by BeryJu** [comment]
98% sure this is caused by the policy result being cached, this can be configured by editing the binding (*Edit Binding* next to the User Delete stage in your screenshot), and setting `Re-evaluate policies` to true. This will cause the policy to be re-evaluated after the first stage.

Additionally, you may want to disable `Evaluate on plan`, as running that policy during a Flow plan will execute your policy again.

P.S. please don't use PDFs to report bugs on github; it makes everything a lot harder to search for, and opening unknown PDFs can have security implications

**Comment by BramBeeyond** [comment]
Thanks for your reply @BeryJu and I will not use PDF anymore. But unfortunately I already set (didn´t mention that yet):
`Re-evaluate policies` to true and I disabled `Evaluate on plan`. So therefore I think it actually is a bug.

**Comment by BeryJu** [comment]
My bad, I kinda forgot about this, @BramBeeyond could you export the flow from authentik (click on the name and then export) and upload the .akflow file here?

**Comment by BramBeeyond** [comment]
We upgraded from version 2022.3.3 to version 2022.4.1 and somehow that fixed this issue.
Thank you for your response & thanks for all your work for Authentik :)
