### ISSUE TITLE
Prometheus metrics endpoint causes memory-leak

### ISSUE THREAD

**Issue by SebastianRzk** [goauthentik/authentik#2784]
**Describe the bug**
A prometheus pulls the data from the :9300/metrics port.
The returned prometheus file gets larger and larger over time, and authentik needs more and more CPU for the response. Until authentik crashes (and gets restarted by environment). Then the response is small again and grows again. 

![image](https://user-images.githubusercontent.com/5215946/165555594-ab6fd914-b00b-421d-9b50-48190e8745b0.png)

![image](https://user-images.githubusercontent.com/5215946/165555741-69a8fcbd-e174-4bf7-8cd4-d551e6c12a57.png)

![image](https://user-images.githubusercontent.com/5215946/165555818-88a41f35-1c02-4c2d-b597-7d29491a66cf.png)

I restarted authentik and monitored the returned filesize in the first few hours. The size of the /metrics endpoint response grew fast:

![image](https://user-images.githubusercontent.com/5215946/165744946-83f91d99-0d22-4889-9ae8-3b3e1b138160.png)

**Version and Deployment (please complete the following information):**
 - authentik version: verified on versions 2022.4.1, 2022.3.X, 2022.2.X
 - Deployment: docker-compose

**Additional context**
~ 10 applications + provider (oidc)
~ two-digit active user number

**Comment by SebastianRzk** [comment]
I've just verified this behavior on a much smaller installation:
~ 3 applications
~ 3 active users
Response body growth is much slower, but measurable. measurement period: 30 days.

**Comment by SebastianRzk** [comment]
Here are some more infos about the metrics response

    $ wc debug7
      6284  16850 781977 debug7
    
    $ cat debug7 | grep authentik_models | wc -l
    2177
    
    $ cat debug7 | grep authentik_policies | wc -l
    1984
    
    $ cat debug7 | grep django_http_requests | wc -l
    1480

**Comment by SebastianRzk** [comment]
## Update on new version 2022.5.1 / 2022.5.2

I've seen that you commited changes and they are in the current version 2022.5.1 and 2022.5.2  right?

The problem still consists:

![image](https://user-images.githubusercontent.com/5215946/170682176-28b98411-e25e-47c3-b08d-a8245bc95333.png)


## Here is some additional information:

### Number of Metrics:

    cat debug9 | cut -d'{' -f1 | sort |  uniq -c | sort
    [...]
    1117 authentik_system_tasks
    1156 django_http_requests_latency_seconds_by_view_method_bucket
    1215 authentik_policies_execution_time_bucket
    1920 authentik_policies_build_time_bucket
    8643 authentik_models

### Total filesize

    $ cat debug9 | wc --bytes | numfmt --to=iec-i --suffix=B --padding=7
    1,8MiB

### File size by metric
    
    $ cat debug9 | grep authentik_models | wc --bytes | numfmt --to=iec-i --suffix=B --padding=7
     778KiB
    
    $ cat debug9 | grep authentik_policies_build_time_bucket | wc --bytes | numfmt --to=iec-i --suffix=B --padding=7
     297KiB
    
    $ cat debug9 | grep django_http_requests_latency_seconds_by_view_method_bucket | wc --bytes | numfmt --to=iec-i --suffix=B --padding=7
     142KiB
    
    $ cat debug9 | grep authentik_system_tasks | wc --bytes | numfmt --to=iec-i --suffix=B --padding=7
     157KiB

## General remarks:

I am surprised that there are subs (=usernames) in the prometheus metrics. I am even more surprised that there are metrics for every user and every application. 

So I guess the current workload of the metrics = `users x applications x  15 (number of metrics)` and a `n x m` complexity is not very suitable for a metrics endpoint? But maybe I don't get the real intention of most of the metrics. @BeryJu 

For me it would be okay if I have an application / provider scoped metric.

**Comment by BeryJu** [comment]
good points, a lot of those metrics were added to graph the amounts of objects created, but they probably aren't really all that useful

the issue with the pid is what I was trying to fix with https://github.com/goauthentik/authentik/commit/254249e38b97f4e94585f0fe30fd5d3ccd2dd4f1, but it caused some other issues since whenever a worker process was killed, it could often happen that it's metrics state was not saved cleanly, and that would cause issues on worker start

currently, `worker_exit` is called when a worker exists and `mark_process_dead` is supposed to clean up metrics for that PID, but from reading the prometheus client code that seems to only clean up some files

**Comment by SebastianRzk** [comment]
I understand what you want to to do, but I think prometheus is not designed like that.

Labels are key-value pairs, that can only be added and not removed. So the client-library behaves compliant by not removing outdated pid-values.

https://prometheus.io/docs/practices/naming/

So there is a warning pat in the official documentation that explains that:

![image](https://user-images.githubusercontent.com/5215946/170690381-2481210a-5c62-419c-8c72-f34e9c0199cd.png)

**Comment by SebastianRzk** [comment]
Are two different concepts mixed up here?

* Prometheus is for regular monitoring, e.g. CPU, RAM or similar.

* There is another type of monitoring: event based monitoring. For example, events are logged and processed by an ELK stack (elastic search, logstash, kibana).

**Comment by BeryJu** [comment]
Yeah true, I added a lot of these metrics when I was quite new to prometheus, and now reflecting on them there's a lot labels in there that don't really make sense as a prometheus label. I'll create a PR (released with 2022.6) later to clean a lot of them up/remove high-cardinality labels, please feel free to comment on that with your opinions too.

**Comment by BeryJu** [comment]
I also still think that the per-process files should be cleaned up when the worker is gone, as currently where this isnt the case, the files add up and will be picked up by any random worker when a metrics request is received, thus causing the memory leak.

The per-pid files should be removed as the metrics still exist in prometheus, but because the worker with that PID is gone, the metrics won't change anymore, and as such there's a growing amount of static metrics output.

Also (and this is probably quite subjective), I dont think the PID should be included as a label at all, since they are short-lived and can be duplicate in different containers, and its not something one would query on, but that's probably a different story.

**Comment by SebastianRzk** [comment]
Hi @BeryJu .
It looks much better now. With version 2022.6.2 I was no longer able to measure the problem.

If I'm missing any metrics, I'll get in touch or make a pull request right away. Thanks for the offer :)
