### ISSUE TITLE
2022.5.1 healthcheck on server fails

### ISSUE THREAD

**Issue by eleith** [goauthentik/authentik#2915]
**Describe the bug**
docker health check on authentik server fails with output `curl not found`, everything else seems to be working, just the healthcheck itself fails

**To Reproduce**
run authentik with the default docker-compose.yml and run `docker inspect ...` on the server container to see the health of the server container and the above error.

**Expected behavior**
healthcheck reports no error

**Version and Deployment (please complete the following information):**
 - authentik version: [e.g. 2022.5.1]
 - Deployment: [e.g. docker-compose]

**Additional context**
running `apt install curl` on the server container does resolve the issue and docker reports the container is now healthy

**Comment by eleith** [comment]
this seems to have introduced the error: https://github.com/goauthentik/authentik/commit/a7a7b5aacb082d1fdef70d039663b9eec7e25939#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L51

**Comment by agrimpelhuber** [comment]
@eleith, thanks for pointing this out, along with the (temporary) fix with `apt install curl`. This was particularly important for me, because the update 2022.4.1 to 2022.5.1 broke my whole Authentik installation!

As it turns out, "everything else seems to be working" did not apply to me. As far as I can tell, Traefik refuses to initialize an unhealthy container, so the 2 routes for the Authentik Server container never came up in Traefik. This just as an information for people who experience the same.

I was stupid enough not to realize that the health check was not the symptom of a deeper issue, but actually the root cause.

**Comment by cybermcm** [comment]
@agrimpelhuber: thanks for your analysis. I encountered the same with my installation today, reverted to 2022.4.1 because I couldn't access the frontend any more (had to restore the database, 2022.5.1 seems to change the db, rolling back isn't that easy.
Thanks again!

**Comment by BeryJu** [comment]
FYI 2022.5.2 is out which fixes this issue
