### ISSUE TITLE
Do you even test you application basic functionalities are working before releasing

### ISSUE THREAD

**Issue by Rishang** [goauthentik/authentik#2921]
From past 3-4 version there are various issues in authentik basic funconalities:

It's ok to keep the releases late, but stable - rathere than makeing breaking changes break application basic components

[2022.5.2 ] -> api not responding timeout to various functionality, making admin panel useless

[2022.3.2 ] -> 400 bad request for policy bindings

**Comment by xlanor** [comment]
You can always submit a PR to add more test cases that will add the coverage that you feel is missing.

**Comment by BeryJu** [comment]
I try my best to not introduce breaking changes, there's also only primarily me working on the code, and that in my spare time, so things are bound to break. 

Imo if authentik is a piece of software that is "business" critical in your environment, it makes sense to not always be on the latest version or wait to upgrade, and have backups in case something does not work

Additionally I would appreciate more constructive error reports that actually help me and the community find and fix issues instead of rants like this
