### ISSUE TITLE
Property mapping for web UI notifications.

### ISSUE THREAD

**Issue by dugite-code** [goauthentik/authentik#2980]
**Is your feature request related to a problem? Please describe.**
I am implementing login notifications using the Generic webhook  for the Policies `Policy authentik-core-login` and `Policy authentik-core-login-failed` with a webhook mapping.

The current behavior also sends the raw unformulated event json to the web notification for the user group targeted by the notifications.

**Describe the solution you'd like**
Add the web notifications as a transport to be able to manually apply a property mapping to web notifications so it formats nicely like just like the webhook.

**Describe alternatives you've considered**
A method of excluding the property mapped webhook from the web ui notifications.

**Additional context**
![image](https://user-images.githubusercontent.com/12742064/170913487-7f7788ae-280f-47a4-aa55-e0dd414a587e.png)
![image](https://user-images.githubusercontent.com/12742064/170913627-1182d578-bfe3-4726-908b-27e91a7c7f57.png)

Property Mapping
```python
try:
    event_user = notification.event.context["username"]
except:
    event_user = notification.event.user["username"]

if notification.event.action == "login_failed":
    priority = 7
    severity = "warning"
elif not ak_is_group_member( ak_user_by(username=event_user), name="gotify-users" ):
    priority = 0
    severity = notification.severity
else:
    priority = 1
    severity = notification.severity

geo_uri = f"geo:{notification.event.context['geo']['lat']},{notification.event.context['geo']['long']}?q={notification.event.context['geo']['lat']},{notification.event.context['geo']['long']}"

title = f"{severity} from authentik {notification.event.action.replace('_', ' ')}".capitalize()

message = f"New {notification.event.action.replace('_', ' ')} for {event_user} was detected coming from {notification.event.context['geo']['city']} {notification.event.context['geo']['country']} from the IP address: {str(notification.event.client_ip)}".capitalize()

g_notif = {
    "title": title,
    "message": message,
    "priority": priority,
    "extras": { "client::notification": { "click": { "url": geo_uri } }},
}

return g_notif
```

**Comment by ich777** [comment]
Sorry that I use this issue instead of opening a new one but it seems to be the right place for that.

@dugite-code & @BeryJu I'm running into a weird issue when using the example from above that messes with my notification priority when `notification.event.context["username"]` is used but everything is working as it should with `notification.event.context["email"]`.

I'm not entirely sure what causes this, maybe someone can help here.

When using:
```
try:
    event_user = notification.event.context["username"]
except:
    event_user = notification.event.user["username"]
```
    
 I get messages like that (this is a alert message and should not be read because it is actually a notice):
![grafik](https://github.com/goauthentik/authentik/assets/28066518/4174b430-1da8-4356-a322-2afcf86c6cf1)

But when I use:
```
try:
    event_user = notification.event.context["email"]
except:
    event_user = notification.event.user["email"]
```

Then I get messages like that (this is a normal notice message and how it should look like):
![grafik](https://github.com/goauthentik/authentik/assets/28066518/0366ab90-05ab-4ffd-b29c-32e15544ce7e)
