### ISSUE TITLE
Add option to remove upstream server details in Bad Gateway message

### ISSUE THREAD

**Issue by raldnor** [goauthentik/authentik#3314]
When a backend is unreachable (for example when the backend server is down) Authentik responds to the web user with a 'Bad Gateway' message. This message includes the internal IP address and port. From a security perspective this exposes internal network information to outsiders and should be prevented (comparable to header information in web servers).

It would be nice to have a configuration option to disable these details in the message and instead show a generic message. 
It also seems that the Bad Gateway error message ignores any customization because the default Authentik template design is shown.

So please:
- Add a configuration option to disable backend details in error messages disclosed to users
- Make sure that Authentik error messages in HTML use same customization as the rest of the templates (e.g. logo, background)

![authentik_bg_msg](https://user-images.githubusercontent.com/10779142/181114315-7bb81b72-597b-4ab8-a954-484751e60122.png)

**Comment by BeryJu** [comment]
The error is only shown to authenticated users, but I do agree with your point that maybe not everyone should get the full details

The reasoning why theming changes don't apply is because this page is statically rendered by the outpost, which currently does not have all that info (also might not have access to the same URLs)
