### ISSUE TITLE
Webauthn with mobile android

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [goauthentik/authentik#3642]
**Is your feature request related to a problem? Please describe.**

Webauthn with a mobile android with built-in fingerprint reader does not work.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ashuio** [comment]
Just tested and it works on my end flawlessly like any other Security Device, Using chrome on Android 13 on a Samsung S22 Ultra

**Comment by Cookie-Monster-Coder** [comment]
It seems like it's working for 2 factor now.

But now when I try to use it as a security key on the main login page it throws an error saying "there aren't any passkeys for domain.com on this device."

**Comment by JackBailey** [comment]
Same here, 2FA is fine but passwordless throws the `there aren't any passkeys for domain.com on this device.` error

**Comment by PDXUser** [comment]
Can confirm on my Galaxy A13 5G - same error message in Google Chrome, and Firefox current editions.

**Comment by v411e** [comment]
My guess is, that this happens if you have no identification stage before the webauthn Authenticator Stage. In this case, Authentik does not know the user and might ask for a passkey where the user is included, which we do not have set up on our Android devices.

**Comment by PDXUser** [comment]
With Google Chrome, Firefox and Vivaldi you sure can add a WebAuthn Passkey.  With the 10.2 release.  I tested this against DuckDuckGo's browser and it doesn't understand it so that's a nogo.  

To set this up, you basically, log into the account as usual, add it as a new Webuathn device and it will go from there.   You will be able to unlock with fingerprint or other biometric method you use.  

This does seem to be a duplicate issue though of [issue 7267 ](https://github.com/goauthentik/authentik/issues/7267)  concerning Yubikey.

**Comment by BeryJu** [comment]
This should be fixed in 2023.10 and later, could you re-test this? @Cookie-Monster-Coder
