### ISSUE TITLE
Federate with Google ok, but still need to prompt username/email

### ISSUE THREAD

**Issue by adlp** [goauthentik/authentik#3709]
**Describe your question/**
When I try to login/enroll (first time I'm connecting) to my authentik with my gmail account, I've to "select a username", truly, to give my login or my gmail email. (I try to give some false infomation, it's KO, when I give the correct one, it's ok)

I would like : that I haven't to feed this field, and the user is created with email as login

**Relevant infos**
I've federate for the fun, with my company azure AD, my authentik user is create without intervention

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.9.0 (but I've add the same issue with 2022.8.2
 - Deployment: docker-compose

**Additional context**
I've too try created my own flow/stage enrollement, nothing more intelligent, I've create another OAuth OpenId federation (but this time without choosing Google Provider type..) : Same problem

In debug mode for those both federation I can see this error: 

Sep 30 18:29:41 localhost authentik.foo.bar1828]: {"auth_via": "unauthenticated", "event": "Created new user", "flow_slug": "enrollement-4-gg-auth", "host": "authentik.goo.bar", "level": "debug", "logger": "authentik.flows.stage", "pid": 21, "request_id": "7302c7709a834418b26156f43744bf7d", "stage": "enrollement create user if needed", "stage_view": "authentik.stages.user_write.stage.UserWriteStageView", "timestamp": "2022-09-30T16:29:41.412499"}
Sep 30 18:29:41 localhost authentik.foo.bar[1828]: {"auth_via": "unauthenticated", "event": "Aborting write to empty username", "host": "authentik.foo.bar", "level": "warning", "logger": "authentik.flows.stage", "pid": 21, "request_id": "7302c7709a834418b26156f43744bf7d", "stage": "enrollement create user if needed", "stage_view": "authentik.stages.user_write.stage.UserWriteStageView", "timestamp": "2022-09-30T16:29:41.412768", "user": "<User: >"}

**Comment by amanzella** [comment]
@adlp I ran across this last night and ended up figuring out a way to make this work.

Edit Prompts
1. Go to Flows & Stages - Prompts
2. Edit the username prompt
3. It should look like this 
![image](https://user-images.githubusercontent.com/14251074/210849044-89ae06ac-a96b-4bc0-b4b7-73df61584c10.png)

Create a Policy Expression
1: Go to Customisation - Policies
2: Create a new Expression Policy
3: Name it whatever you'd like. (I named my Set username to email)
4: Put the following Expression 
```
request.context["prompt_data"]["username"] = request.context["prompt_data"]["email"]
return True
```
It should look like this

![image](https://user-images.githubusercontent.com/14251074/210849558-790c8810-a1ac-4721-b6ea-fc2ab51d58b5.png)

Edit Flow

1. Go to Flows & Stages - Flows
2. Click the flow you are using for Enrollment (i.e. default-source-enrollment)
3. Click State Bindings
4. The first stage under stage bindings should be default-source-enrollment-prompt
5. Click Edit stage and make sure the username field is selected and no validation policy (I haven't played with those yet)
6. Click the expand arrow next to the default-source-enrollment-prompt
7. Select Bind existing policy
8. Select the policy that you created in the previous steps. ie. Policy Set username to email
9. Your stage bindings should now look like this
![image](https://user-images.githubusercontent.com/14251074/210850479-e798d7f3-7a26-4cd0-a1e6-4fdc01920e1b.png)

Now when you click the google icon on the login page to log in/enroll, it will fill in the username field with the google user's email address. They aren't able to edit it and only able to hit continue.

Let me know if that works for you. I also went a little further and disabled editing the username and password so that users can't change any of them. I deleted the change password from the user settings as I discovered that once logged in with the google account, you can change the password and then log in locally with the user/pass. I didn't want any local login so that if we kill a user's account in google, they can't log in locally. I haven't tested to confirm that it does stop someone, but I assume it does and will test when we delete a user in google. I also added TOTP to the enrollment and login and will start testing today to ensure it does what we want.

**Comment by BeryJu** [comment]
Cheers, I've been meaning to add this to the docs for a bit, what @amanzella suggested is basically the best solution, so I've added it to the docs here https://goauthentik.io/integrations/sources/google/#username-mapping

**Comment by Welleee** [comment]
Hi @BeryJu @amanzella, is it possible to do this with authentik registration? I have a enrollment flow where I don't need the username, just the email
