### ISSUE TITLE
What should be displayed in the ui here?

### ISSUE THREAD

**Issue by Hansanghyeon** [goauthentik/authentik#3794]
What should be displayed in the ui here?

What should I get when I press this button on the code display?

<img width="1080" alt="스크린샷 2022-10-17 오후 12 49 13" src="https://user-images.githubusercontent.com/42893446/196085688-379097ee-dfaa-4343-bbcb-e6fde83ee0c3.png">

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.09
 - Deployment: docker-compose

**Comment by a-camacho** [comment]
Same problem

**Comment by BeryJu** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1932513/196146723-53a9e35d-0330-48f5-9d5f-e030a26e0466.png">
 That panel is supposed to show the API Requests, it being blank is fixed by https://github.com/goauthentik/authentik/commit/52e05666955ffa1260f4fe2c7d7708f4e5ab7f66 and will be included in the next release
