### ISSUE TITLE
Plex login doesn't work on mobile

### ISSUE THREAD

**Issue by jonathann92** [goauthentik/authentik#3822]
#### Describe the bug
When I try logging in with plex on mobile, the plex login screen never shows up. I am able to log into authentik with plex auth using my computer.

Here is the documentation that I followed to setup plex login with authentik.
https://goauthentik.io/integrations/sources/plex/

#### To Reproduce
1. Go on iPhone 12 Pro iOS 15.6.1 (I used safari and brave in private mode)
2. Go to my traefik reverse proxy url that points to authentik
3. Click on the plex icon
4. This is where the issue happens, the plex login page doesn't load

**Expected behavior**
I expected for the plex login screen to show up and be able to login with it.

**Screenshots**
Sorry I don't have a screenshot, but it is stuck on the screen "Authenticating with Plex..." with a spinning circle forever.

#### Logs

This was the only log that printed when I clicked on the Plex icon.

```txt
{"event":"/static/dist/flow/PlexLoginInit-4a6a3433.js","host":"authentik.mydomain.com","level":"info","logger":"authentik.router","method":"GET","remote":"172.21.0.7","runtime":"0.967","scheme":"https","size":12783,"status":200,"timestamp":"2022-10-19T20:54:02-07:00","upstream":"","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1"}
```

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.9.0
 - Deployment: docker in unRaid

**Additional context**
I have the google auth working on both mobile and a computer.

Overseerr uses plex auth to log into the application. I noticed that when I click “sign in” it’ll open a new tab for the plex login.

**Comment by samip5** [comment]
I don't know if it's even supposed to work in private-mode.

**Comment by jonathann92** [comment]
It happens in regular mode and private mode. I just stated private mode because cache is usually the cause of a lot of browser issues.

**Comment by babariviere** [comment]
After a bit of investigation, it looks like this issue is only for iOS (I have tried it on Android, it works as expected).

Apparently, `windows.open` calls doesn't work in async code block for iOS, and since authentik is doing it in async blocks, like [here](https://github.com/goauthentik/authentik/blob/8ed2f7fe9ef1694666b0fe244e67ddc635e57c36/web/src/flow/sources/plex/PlexLoginInit.ts#L39).
I think this needs a bit of refactor to create the window out of this call, probably by passing a reference to the window like replied here: https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari

**Comment by jonathann92** [comment]
@babariviere thanks for making the changes!

**Comment by babariviere** [comment]
No problem!
