### ISSUE TITLE
OAtuh user identifier 'username' instead of 'email'

### ISSUE THREAD

**Issue by Dima-Kal** [goauthentik/authentik#3852]
**Describe your question/**
I am doing integration with Portainer, with 'email' as user identifier it works and i'm able to login, but i don't like logging in with email address as user name

As far as i understood there are 2 options:
https://goauthentik.io/docs/flow/stages/identification/#user-fields
'email' and 'username'
in Proxmox integration example i see that 'username' was used:
https://goauthentik.io/integrations/services/proxmox-ve/

when i tried to use 'username' in portainer i get an error:

[DEBUG] - OAuth authentication error: failed to extract username from oauth resource"

What am i doing wrong?

**Comment by BeryJu** [comment]
the `email` and `username` fields from the identification stage are different than the fields that are in OIDC

the claim for OIDC that contains the username is `preferred_username`

**Comment by Chrispikaan** [comment]
Hi, i'm also trying to use the username in Portainer instead of the email address.
Example. Username is John and the email is John.Baker@example.com.
Email works with user identifier: email
and Scopes: email openid profile

But how can I use the username as user identifier? I tried user and username but it doesn't work.
What am I doing wrong?

![afbeelding](https://github.com/goauthentik/authentik/assets/99992200/74d07484-947d-4aef-98a5-9d91c8420035)

**Comment by BeryJu** [comment]
See https://docs.goauthentik.io/integrations/services/portainer/
