### ISSUE TITLE
Blueprint application does not remove flow stages

### ISSUE THREAD

**Issue by sdimovv** [goauthentik/authentik#3980]
When applying an updated blueprint to an existing flow any stages that have been removed from the blueprint YAML are not removed from the flow.

To reproduce:
1. Start with a clean authentik 2022.10.1 release
2. Complete initial setup, login, etc.
3. (Optional, did it just to confirm it is not due to a dependency on something else) Delete all flows, tenants, policies, stages, prompts. etc.
4. Apply just the [default authentication flow](https://github.com/goauthentik/authentik/blob/3306003f0e0ac350eaecf3ba3584fcf6c6f4a4d1/blueprints/default/10-flow-default-authentication-flow.yaml) from the default blueprint folder.
5. Confirm the blueprint has been applied
6. Modify the default blueprint by commenting out the MFA stage and its corresponding stage bind. Optionally, modify the flow's title and name strings to easily confirm it has been re-applied
7. Re-apply the blueprint
8.  Confirm the blueprint has been re-applied and it still has the same number of stages (4).
9. Delete the flow
10. Re-apply the blueprint
11. Confirm the blueprint has been re-applied but the flow has 1 stage less (3).

**Comment by BeryJu** [comment]
The blueprints are very much imperative more than declarative, authentik doesn't keep state of which objects a previous blueprint had and automatically delete things that aren't managed anymore. However this will be possible with #4061

**Comment by sherif-fanous** [comment]
@BeryJu Sorry to revive such an old issue but I want to understand the current status of blueprints reconciliation and can't find that documented

Does Authentik execute a Reconciliation Loop when Blueprints are used?

For example, Kubernetes has a reconciliation loop that monitors the current state of the resources and compares it to the desired state and in case of any observed drift, Kubernetes makes the necessary changes to bring the resources to its desired state.

The reason I ask is because I declared a Blueprint for a Provider and Application

1. I deployed the Blueprint. After restarting the Worker pod I could see that the Provider and Application were created in Authentik ✅
2. I made changes to the Provider and Application from the WebUI. The changes persisted ❌ . I was expecting that the Worker pod would reconcile the resources and determine that since the Blueprint (Desired state) was different than the current state that the Provider and Application would be reconciled back to the state defined in the Blueprint
3. I deleted the Blueprint. After restarting the Worker pod I could still see the Provider and Application in Authentik ❌ . I was expecting that the Worker pod would reconcile the resources and determine that since the Blueprint was deleted that the corresponding Provider and Application must also be deleted

Is my understanding incorrect or is am I doing something wrong? My end goal is to have my Authentik environment completely configured declaratively and that any changes made to these declarations would always be considered the desired state. 

Thanks
