### ISSUE TITLE
How to do change client audience / client scope?

### ISSUE THREAD

**Issue by DrZoidberg09** [goauthentik/authentik#4021]
Hi there,

I want to use Nextcloud OIDC Login with Authentik. To use it also for external WebDAV access, this should be done when using Keycloak:

> 
>   Configuration for WebDAV access
> 
>   The underlying OIDC library ensures, that the aud property of the JWT token contains the configured Nextcloud client ID (config option oidc_login_client_id). However, when obtaining an access token for a user with a client other than the Nextcloud client (e.g. using rclone), the aud property does not contain Nextclouds client ID. Thus, the login would fail. The following steps ensure, that access tokens obtained with your client always contain your Nextcloud client in the aud property.
>     Go to Client Scopes
>     Add new client scope, call it nextcloud.
>     Under Mappers create a new mapper of type Audience and ensure that Included Client Audience contains your Nextcloud client. Click Save.
>     Finally, go to Client > your-client-to-obtain-access-token > Client Scopes and add the new nextcloud scope.

What is the equivalent way doing this with Authentik?

Thank you so much for any hint!

**Comment by BeryJu** [comment]
in authentik, the `aud` claim is set to the provider's client_id by default, so this configuration shouldn't be required. It is also possible to modify the `aud` claim by returning it from a Scope mapping which is selected in the provider

**Comment by SpiderD555** [comment]
@DrZoidberg09 You may want to try this:
Put this into Nextcloud configuration:
```
'oidc_login_webdav_enabled' => true,
'oidc_login_password_authentication' => true,
```
Then setup Authentik application password under user settings --> "Tokens and app passwords". Normal user password assigned to the account won't work (that is the current design).
Unfortunately as of now version 2024.2.3 does not support infinite duration token/app passwords.
As far as I can tell [this is part of 2024.4.0-rc1 due to recent PR](https://github.com/goauthentik/authentik/pull/7410), so you may as well try the unstable docker while waiting for the stable release.
