### ISSUE TITLE
Unauthenticated Paths not working correctly

### ISSUE THREAD

**Issue by Surgical71** [goauthentik/authentik#4154]
Unauthenticated Paths not working correctly when using a App like Uptime Khuma

**Expected behavior**
Epected to be able to see status page in Uptime khuma without needing to authenticate with Authentik

**Screenshots**
![image](https://user-images.githubusercontent.com/80483431/205613024-2de46f45-dfea-4058-914f-fb48211f1413.png)
![image](https://user-images.githubusercontent.com/80483431/205613060-2ee9352e-ad48-4e61-ab96-9409bbad7559.png)
![image](https://user-images.githubusercontent.com/80483431/205613091-adcd4363-d5f3-4002-b07a-44c96882dfcf.png)

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.10.1
 - Deployment: Docker-compose

**Additional context**
I am able to see the status page once I authenticate with Authentik. But the idea is to have the status pages available when not authenticating and protect the login/admin panel

**Comment by yeorinhieut** [comment]
Still not working

**Comment by lucaam** [comment]
I know this is quite old now but since I ended here for the same issue, I think it worth mentioning that I fixed the issue using a larger list of unauthenticated paths for Uptime Kuma:

```
^/$
^/status
^/assets/
^/assets
^/icon.svg
^/api/.*
^/upload/.*
^/metrics
```

This list is provided in the [official doc](https://docs.goauthentik.io/integrations/services/uptime-kuma/).

@yeorinhieut I hope this is useful for you!
