### ISSUE TITLE
Authentik without Docker / Kubernetes (LXC)

### ISSUE THREAD

**Issue by cuthulino** [goauthentik/authentik#4273]
First, i love authentik. I can realise everything in my homelab with SSO. Thanks for that @BeryJu ! 
 
At the moment i am thinking about switching everything from Docker to LXC. 
I use Proxmox and my setup at the moment is "PVE -> VM -> Docker -> authentik" 
I want to switch to "PVE -> LXC -> authentik".  
 
In the Docs there is no install section for a bare metal install.
Is it supported to install authentik in an lxc container? 
How to do it? (Just go through the Dockerfile?)

Or do i really have to run Docker in LXC for Authentik?

**Comment by maxwlang** [comment]
Wanted to add to this. Helm and docker are useful, but having the ability to install this raw in a VM or LXC would be awesome. I'm currently having issues getting the docker compose version to start with failure to connect to postgres as well. I would be able to decouple from the included redis and postgres instances and connect to my hosted versions, combining databases and potentially avoiding the issue I'm currently hitting entirely.

**Comment by information-redacted** [comment]
Hey, I ended up making a few scripts that initialize an Authentik instance as of c2b4d14af5c0cba73550195a10c519775ac4173f; Please note that they're extremely unstable (during testing, compiling python segfaulted for some setups) but do result in a working environment in most cases!

https://github.com/information-redacted/authentik-bare-metal

**Comment by thoemie** [comment]
@authentik-bot  Are there any plans to make bare-metal installation possible and supported?

**Comment by bastrian** [comment]
I would be interested too running it on bare-metal. Docker is fine and everything, but it simply does not fit into my environment.

**Comment by derrickmehaffy** [comment]
Adding to this that I also would love to see non-docker/k8s install options especially if it allows me to use my pre-existing database and Redis clusters.

Also a proxmox user and at the very least having an LXC container would be nice but ideally bare metal/VM installs would be best.

**Comment by KissmanCZ** [comment]
Same here, would be nice to have bare metal / VM installation officially supported because Docker/Kubernetes is not secure enough for many companies. Also 1 year without any reply in this topic (even just a message that you will not support this) from developers is also not great sign. All this together is just reason, why we never consider this solution as serious replacement for IdP.

**Comment by BeryJu** [comment]
There are several community-maintained solutions for this. At this time we're not planning to offer this directly due to the increased amount of support for different linux distributions/setups

**Comment by lthieman** [comment]
Not offering other options than Docker is an unfortunate choice.

**Comment by dharmab** [comment]
Saddened to hear this - none of my machines run Docker Engine anymore (containerd/podman ❤️) so I will have to find something else instead.

**Comment by dom6770** [comment]
As someone who uses LXC for services like this, this decision is indeed quite unfortunate. Docker in LXC is suboptimal to say at least.

Every other project is able to offer a bare-metal install, except authentik.

I hope this decision will be revised. 
You don't need to support every distro, Debian and RHEL would cover already many.

**Comment by 0x464e** [comment]
> There are several community-maintained solutions for this.

Does anyone know if this is actually true and are they usable? I'm unable to find any, except for the clearly abandoned one mentioned here at the top.

I found this issue with a Google search and I also want to say how unfortunate it is that I must have docker for Authentik. I'm not against using docker and I happily run multiple docker containers on my docker vm, but that docker vm is on my server pc, which might need reboots, maintenance, the docker vm itself might need maintenance, or whatever could cause downtime for it, and it shouldn't matter, should be fine. Except it can never be fine for my docker vm to have any downtime, because I'm running Authentik there. Suddenly, I wouldn't be able to access any other services that I authenticate to using Authentik.

On my router box, I virtualize opnsense and have lxcs for all other critical network related services that should be always up (e.g. reverse proxy, cloudflare tunnel, tailscale, etc). Authentik should absolutely be run here as well as an lxc. But it's just very heavy to have to run a whole docker vm there as well just for Authentik, I'm not even sure I'd have the RAM available.

**Comment by rissson** [comment]
So what we actually ship are OCI images, not necessarily to be used with Docker. You could use Podman, or even raw containerd or cri-o if that's your thing, or any other OCI runtime.

On top of that, an OCI image is basically a compressed file system, with some metadata. You could relatively easily extract that filesystem and run authentik from that.

However, maintaining an LXC image currently is too much maintenance for the project, so we won't be doing it for quite some time.

**Comment by CrazyWolf13** [comment]
I'm also saddened to hear this, I'm using Proxmox and not docker.

Though maybe there is not all hope lost, as Proxmox Supports OCI Images since v9.1 (https://forum.proxmox.com/threads/proxmox-virtual-environment-9-1-available.176255/), I'd happy to try it out, but I've not been able to find any doc page or mention here in the github repo, could you point me to the URL or doc of the OCI Image from authentik  @rissson ?

Thanks!

**Comment by rissson** [comment]
A Docker image is an OCI image, so ghcr.io/goauthentik/server:2025.10.3

**Comment by dom6770** [comment]
but that doesn't include the worker, postgresql and redis.

We don't need a maintained LXC, we just need binaries to run without any containers (or a all-in-one OCI image, I suppose)

**Comment by rissson** [comment]
ghcr.io/goauthentik/server:2025.10.3 has the worker in there. Redis is not used anymore since 2025.10, so that's a non issue, and PostgreSQL can be installed however you want, as long as authentik has a database it can connect to.

**Comment by Redeeman** [comment]
why couldnt there just be instructions on how to build and configure, and let it be up to the users to follow them, kinda like most things are able to do?

**Comment by rissson** [comment]
You can look at https://github.com/goauthentik/authentik/blob/main/lifecycle/container/Dockerfile for how we build authentik. One extra step is that you need to run `make gen-client-ts gen-client-go` beforehand. Otherwise, everything is in there.

We don't want to duplicate this information in a separate documentation to avoid it becoming stale.

**Comment by aspx1981** [comment]
Hello,
any update on this,
I read and compared different sw and I was thinking to use Authentik for my personal self-hosted environment, but I'd like to install without docker.
Is there a place where I can start from ?

**Comment by CrazyWolf13** [comment]
@aspx1981 
Depending on how you want to install them, our org maintains a proxmox community script for authentik, which someone contributed, it's basically debian with aome of our custom functions, maybe it's helpful if you want to install it in debian-like environment:

Installation script: https://github.com/community-scripts/ProxmoxVE/blob/main/install/authentik-install.sh
Update script: https://github.com/community-scripts/ProxmoxVE/blob/main/ct/authentik.sh

Our custom functions like `setup_yq` or such things: https://github.com/community-scripts/ProxmoxVE/blob/main/misc/tools.func

But I agree, it would be much better, if authentik would just release some sort of packaged deb, it would make things so much easier, and this does not only apply to homelabs, some enterprises just don't want docker, some may have proxmox and therefore prefere something lxc-native.

**Comment by aspx1981** [comment]
Thanks a lot for your link @CrazyWolf13 ,

Dear @BeryJu,
sorry to ask you again, but after two years is it possible you rethink about "authentik-server" deb package support ?
authentik repo with other deb packages is already there (https://pkg.goauthentik.io).
could you please reopen this feature request and let community vote for it ?

thanks
