### ISSUE TITLE
Simulate GitLab SSO

### ISSUE THREAD

**Issue by mivalsten** [goauthentik/authentik#4458]
**Describe your question**

Hi team!
I would like to use Authentik to log in to mattermost team edition, which only allows gitlab as identity provider. There is a way to do this [with keycloak](https://medium.com/@mrtcve/mattermost-teams-edition-replacing-gitlab-sso-with-keycloak-dabf13ebb99e), but I would prefer to use Authentik.

**Version and Deployment (please complete the following information):**
 - authentik version: 2022.12.1
 - Deployment: docker-compose

**Comment by MDXDave** [comment]
You can already use authentik for this. In the following i use the domain `sso.example.com` as the authentik instance.

First you need to create two property mappings (scope mapping; https://sso.example.com/if/admin/#/core/property-mappings):
```
Name: mattermostId
Scope name: id
Expression: return { "id": hash(request.user.username) }
```

and 

```
Name: username
Scope name: username
Expression: return { "username": request.user.username }
```

Then you need to create a new application with oauth provider and assign the created property mappings to it:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/6099976/213440647-d40b878d-2563-48f8-860e-6e79836b5ef7.png">

As last you need to edit the mattermost config file (if you are using docker compose, the `config.json` file should be located at `/opt/mattermost/volumes/app/mattermost/config`). Replace the GitlabSettings section with the following:

```json
"GitLabSettings": {
        "Enable": true,
        "Secret": "AUTHENTIK CLIENT SECRET",
        "Id": "AUTHENTIK CLIENT ID",
        "Scope": "",
        "AuthEndpoint": "https://sso.example.com/application/o/authorize/",
        "TokenEndpoint": "https://sso.example.com/application/o/token/",
        "UserAPIEndpoint": "https://sso.example.com/application/o/userinfo/",
        "DiscoveryEndpoint": "",
        "ButtonText": "",
        "ButtonColor": ""
    },
```

Then restart the mattermost container. 

Please be aware that any existing user that has been authenticated with Gitlab or Email can not be re-used. You need to delete the user (or change the mail address) in order to sign-in with them.

**Comment by BeryJu** [comment]
instead of `hash(request.user.username)`, using `request.user.uid` is recommended for a unique user identifier

**Comment by mivalsten** [comment]
So, do you maybe know why I'm getting below error in mattermost?

```
{
    "timestamp": "2023-01-19 15:43:17.362 +01:00",
    "level": "error",
    "msg": "Bad response from token request.",
    "caller": "web/context.go:117",
    "path": "/signup/gitlab/complete",
    "request_id": "sq789qxkpi879p1ri98p9mqarw",
    "ip_addr": "192.168.0.15",
    "user_id": "",
    "method": "GET",
    "err_where": "AuthorizeOAuthUser",
    "http_code": 500,
    "error": "AuthorizeOAuthUser: Zła odpowiedź z żądania tokena., response_body=, status_code=405, error=EOF, EOF"
}
```

My mappings are configured per instruction:

![image](https://user-images.githubusercontent.com/8068803/213473938-1f0e80d5-7ddb-4c8a-a872-2b4bd2917086.png)
![image](https://user-images.githubusercontent.com/8068803/213474004-61e0534a-2a4e-4af2-99d9-6e37cab7f61c.png)
![image](https://user-images.githubusercontent.com/8068803/213474183-aac8f525-085b-438e-bf97-c6e38a769463.png)

my config looks like this:
```
"GitLabSettings": {
    "Enable": true,
    "Secret": "verySecretString",
    "Id": "NotSoSecretID",
    "Scope": "",
    "AuthEndpoint": "http://authentik.my.fqdn/application/o/authorize",
    "TokenEndpoint": "http://authentik.my.fqdn/application/o/token",
    "UserAPIEndpoint": "http://authentik.my.fqdn/application/o/userinfo",
    "DiscoveryEndpoint": "",
    "ButtonText": "",
    "ButtonColor": ""
},
```

**Comment by BeryJu** [comment]
your URLs are missing a trailing slash, on all of them

**Comment by mivalsten** [comment]
Unfortunately this was not it.

**Comment by BeryJu** [comment]
What error are you getting with correct URLs

**Comment by mivalsten** [comment]
Exactly the same:

```
{
    "timestamp": "2023-01-19 16:03:17.755 +01:00",
    "level": "error",
    "msg": "Bad response from token request.",
    "caller": "web/context.go:117",
    "path": "/signup/gitlab/complete",
    "request_id": "9rq4qh76cbdkfenbyk4e98ucwe",
    "ip_addr": "192.168.0.15",
    "user_id": "",
    "method": "GET",
    "err_where": "AuthorizeOAuthUser",
    "http_code": 500,
    "error": "AuthorizeOAuthUser: Zła odpowiedź z żądania tokena., response_body=, status_code=405, error=EOF, EOF"
}
```

The error says, in polish "Bad response from token request."

**Comment by BeryJu** [comment]
can you also post your updated config?

**Comment by mivalsten** [comment]
`sed`ed my hostname.

![image](https://user-images.githubusercontent.com/8068803/213483473-f127cc5d-f263-40e5-938c-98f7650b5f9b.png)

**Comment by asantinilightia** [comment]
Same here :(
![App](https://user-images.githubusercontent.com/114443429/213592882-30806d29-fa47-468f-8538-7104fa994477.jpg)
![App2](https://user-images.githubusercontent.com/114443429/213592995-2b411d9d-51e3-493a-9779-9814b732213b.jpg)
![App3](https://user-images.githubusercontent.
![App4](https://user-images.githubusercontent.com/114443429/213593182-5f9b89d1-1196-45d6-89e0-45a62c0dad6a.jpg)
com/114443429/213593025-0275c3cb-125f-44a0-a6bd-b17c9d5b9851.jpg)

**Comment by MDXDave** [comment]
Are you sure you assigned the property mappings to your oauth Client? 

If yes, use Postman to debug the userinfo endpoint. Use the same clientId/secret and choose oauth2 authentication within postman.
The response should contain the id and username fields.

**Comment by mivalsten** [comment]
Thank you for the instruction @MDXDave 

![image](https://user-images.githubusercontent.com/8068803/213658137-f7682215-0b87-42f2-9021-8781cdbf60e8.png)

The response contains both username and id.

**Comment by Recycleboy** [comment]
I'm also trying this atm and stuck at the same point :/

**Comment by mivalsten** [comment]
I'm getting closer. I used invitation link and tried logging in this way and got:

```
{
    "timestamp": "2023-01-20 10:24:16.235 +01:00",
    "level": "error",
    "msg": "Could not create user out of gitlab user object.",
    "caller": "web/context.go:117",
    "path": "/signup/gitlab/complete",
    "request_id": "nip4zt6cifnd8c8dsyt566jtqr",
    "ip_addr": "192.168.0.15",
    "user_id": "",
    "method": "GET",
    "err_where": "CreateOAuthUser",
    "http_code": 500,
    "error": "CreateOAuthUser: Nie udało się utworzyć konta z obiektu użytkownika gitlab., json: cannot unmarshal string into Go struct field GitLabUser.id of type int64"
}
```

Looks like `id` should be int64 and it's currently guid.

**Comment by mivalsten** [comment]
And, bingo.

Expression for MattermostID property shoud be `return { "id": request.user.id }`, then it works like a charm.

**Comment by Recycleboy** [comment]
Can you sum up what you did ? I still can't get it to work. Would be awesome!!

**Comment by mivalsten** [comment]
Ok, to sum it up:

I configured everything as per instructions above, copying from Dave's comment.

First you need to create two property mappings (scope mapping; https://sso.example.com/if/admin/#/core/property-mappings):
```
Name: mattermostId
Scope name: id
Expression: return { "id": request.user.id }
and
```

```
Name: username
Scope name: username
Expression: return { "username": request.user.username }
```

Then I added those properties to `Scopes` as per images.

my config.json looks like this:

```
{
  "Enable": true,
  "Secret": "secret",
  "Id": "clientid",
  "Scope": "",
  "AuthEndpoint": "https://authentik.my.fqdn/application/o/authorize/",
  "TokenEndpoint": "https://authentik.my.fqdn/application/o/token/",
  "UserAPIEndpoint": "https://authentik.my.fqdn/application/o/userinfo/",
  "DiscoveryEndpoint": "https://authentik.my.fqdn/application/o/mattermost/.well-known/openid-configuration",
  "ButtonText": "",
  "ButtonColor": ""
}
```

**Comment by Recycleboy** [comment]
Awesome thanks, I've got 1 step further:
![image](https://user-images.githubusercontent.com/91468221/213671474-606b4ca6-35d2-4fef-9612-2e13bdef0737.png)

Rechecking configs rn

**Comment by mivalsten** [comment]
Check mattermost logs and make sure that MattermostID expression is `return { "id": request.user.id }
`, not `uid`.

**Comment by Recycleboy** [comment]
Which mattermost version are you using?

**Comment by mivalsten** [comment]
```
Mattermost Version: 7.5.2
Database Schema Version: 95
Database: postgres
```

**Comment by Recycleboy** [comment]
Alright, got it to work. The answer was quite simple so i feel kinda stupid, but I'll share it anyways if someone is just as stupid as me:
The user you're trying to log in with also must have an E-Mail assigned :D 

Thanks for everything, I really loved the troubleshooting :D

**Comment by lanrat** [comment]
I was able to get this working without modifying the mattermost config by setting up authentik as descrived in @MDXDave 's post https://github.com/goauthentik/authentik/issues/4458#issuecomment-1396893212, and then setting the following redirects in my caddy config for authentik

```
# gitlab emulation
uri replace /application/o/gitlab/api/v4/user /application/o/userinfo/ 1
uri replace /application/o/gitlab/oauth/authorize /application/o/authorize/ 1
uri replace /application/o/gitlab/oauth/token /application/o/token/ 1
```

and setting the GitLab Site URL in mattermost to: `http://authentik.my.fqdn/application/o/gitlab`.

This should survive any  changes mattermost may make to break this in the future.

**Comment by zelogik** [comment]
FYI, sorry to be late but could be useful for some people as documentation.
I haven't found another "clean" way to migrate so...

For a migration of a small team with previous configuration LDAP -> Gitlab SSO -> Mattermost Team
And the new system was Authentik -> Mattermost | gitlab | ...

To keep a "synchronised" id between the old gitlab ID, and the new authentik ID, each user have a attribut like mm_old_id: (get the old gitlab id).

And create a Scope Mapping (like previous post):
scope name: id
expression:
return {
  "id": request.user.attributes.get("mm_old_id", hash(request.user.id)),
}

**Comment by kcck** [comment]
Hello, I just found your post and thank you very much I am getting the following error: 
Error
Token request failed.

Can anyone help me out? I did follow the entire feed and did everything as you posted. Can I get some more tutorial? I am not really well versed into that.

I am also using Unraid with Mattermost docker, based on mysql (which I want to move to Postgres) 
I have Nginx Proxy manager and there if the location config:

<img width="502" alt="Screenshot 2024-04-05 at 23 17 15" src="https://github.com/goauthentik/authentik/assets/9284302/69c82235-b162-449c-9b91-6ef36f73fcab">


  location / {
   # proxy_set_header   X-Real-IP $remote_addr;
   # proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        set $upstream_app 192.168.1.7;
        set $upstream_port 8065;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
#    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }

In Authentik I followed all of your suggestions and here is the error from Mattermost:

{
  "caller": "web/context.go:115",
  "err_where": "AuthorizeOAuthUser",
  "error": "AuthorizeOAuthUser: Token request failed., Post \"https://authentik.com/application/o/token/\": net/http: TLS handshake timeout",
  "http_code": 500,
  "ip_addr": "192.168.1.5",
  "level": "error",
  "method": "GET",
  "msg": "Token request failed.",
  "path": "/signup/gitlab/complete",
  "request_id": "k4idbidn69832hkajf1wgrnjw1c",
  "timestamp": "2024-04-05 23:12:21.655 +02:00",
  "user_id": ""
}


Looking forward to your help.

Thank you

**Comment by mivalsten** [comment]
Hi @kcck, please check your mattermost `config.json` file. I'm suspecting your authEndpoint is wrong. It should be an address of your authentik instance, not `authentik.com`. in my example [above](https://github.com/goauthentik/authentik/issues/4458#issuecomment-1398167386) it says `authentik.my.fqdn`, you need to replace it with your own.

**Comment by kcck** [comment]
Hi. Thank you for your response, it is my FQDN, I just didn’t want to put it. I am also struggling to find the authentik logs that refers to that error.
Also I am wondering if there is an actual need to have the accounts provisioned before the oauth happens. As I am using SAML for Nextcloud and there the accounts aren’t provisioned. Which is what I’d like to do with Mattermost.
Looking forward to your help.
Thanks
Karim

**Comment by radokristof** [comment]
Why you can't re-use previous gitlab authenticated emails/users?
Is it possible to somehow migrate them?

**Comment by mivalsten** [comment]
@radokristof Just to make sure I understand you correctly: You have mattermost users with email authentication, and you want to migrate the accounts to gitlab authentication, is that correct?

If so, you need to edit mattermost database, change "authservice" to `gitlab` and "authdata" to authentik user id.

**Comment by mivalsten** [comment]
@radokristof the one that's in link: `/if/admin/#/identity/users/{ID}`. For ak_admin account that's 1, and then it increments by one.

**Comment by radokristof** [comment]
@mivalsten Thank you, that was it! After updating the `authdata` column to the new userID in authentik, it started to work.

**Comment by EugenMayer** [comment]
Anybody still running this? It seems with newer mattermost editions, the "Scope" is forced to be set to read_user when running the free edition.

Are you all running the enterprise edition to be able to use other scopes in the mm config? Any help appritiated

**Comment by mivalsten** [comment]
I'm still using this on MM 10.5.6 Free Edition. My NGO has 6k volunteers, month of paying for MM enterprise would burn our yearly budget :D

**Comment by EugenMayer** [comment]
@mivalsten fairly sure you would not be able to use authentik with 10.9.1 at all.

AFAICs they use a verify different gitlab integration, that now uses /users to fetch the actual claims, thus the free-edition now only is allow to use read_user as claim (that allows gitlab API access for that lookup).

With 10.9.1 you will also no longer be able to include 'openid' in the scope, since this switches the implementation to the enterprise variant, which then fails to load the provider, since it does not exist. (ref: https://github.com/mattermost/mattermost/blob/dd9a1918e1bf76fbfa41d022a424d76b9e928486/app/oauth.go#L574)

What you can do is using 'Scope=""' to fetch the entire default scope of authentic. This will work, but mattermost no longer cares about scopes/included claims.

So when the first authentication callback is returning, the token will be uses to fetch the 'user attributes' from githubs /user endpoint using this token - and this will fail, since authentik does not implement this. see https://github.com/mattermost/mattermost/issues/28047 and others

IMHO, you integration will not work with newer mattermost. But feel free to prove me wrong, very happy to be wrong here :)

**Comment by mivalsten** [comment]
Ahh, so I see that enshittification of mattermost progresses. Sad.

**Comment by feliscat** [comment]
> [@mivalsten](https://github.com/mivalsten) fairly sure you would not be able to use authentik with 10.9.1 at all.

I've installed mattermost for the very first time today, versoin 10.9.1, and it works with Authentik as described by MDXDave above still.

**Comment by EugenMayer** [comment]
@feliscat ok may i ask:

Just that other users read, @feliscat references this comment here https://github.com/goauthentik/authentik/issues/4458#issuecomment-1396893212 (since there are several of him here)

## Mattermost side
- you also did not expose the discover endpoint like MDXDave?

## Authentik side

Trying to close all the gaps here so others can reproduce too. Would be awesome if you could share

1. Using Scope "" considering the code, makes sense (this is in contrary to the mattermost docs for the gitlab integration, they write read_user is the only value allowed)
2. I assume you exposed all the scope that he described there:
   - openid/profile/email
   - and then in additon both id/username (mapped)
4. even though MDXDave did not write it, I use you configured the redirect URLS, right?:
   - https://<mymattermost.tld>/signup/gitlab/complete
   - https://<mymattermost.tld>/login/gitlab/complete
5. Assuming you are using an RSA signing key (not ECD
6. What did you pick as a subject mode? i assume mattermost is ignoring 'sub' - but still this might matter


feliscat, just to make sure, not doubting you, just trying to reproduce it. The only differences I can spot right now are

1. discovery endpoint not provided (maybe that changes the logic, did not change the code)
2. I'am using an existing user, so I try to match the IDs


**TLTR:**
The setup feliscat references, written by MXDave **does** work out of the box
- set or not set the discovery URL, it does not matter
- I have set the subject mode to 'hased user id'

So if you are just spawning a new mattermost, you are done here. If you are trying to match existing users, read below.

---

**Mapping existing users:**

My existing user in Mattermost (which has never been created using a 'real gitlab OIDC connection) is a 'local user'. Thus the 'id' in the database looks like a hash (not biting), and the remoteId (which is the important one) is empty. And this was the point, when I configured authentic, I used my id as a mapping, not my (empty) remoteId - I did not know about the latter. I was not looking at the DB until now, I extracted the 'id' from the user-profile edit URL.

So I first tried a non-existing user and it worked. To be more exact, it worked while using a discovery URL (so this does not matter), I used 'based on user-id hashed' as subject mode.

But it was still not working with my existing user, even though I set the remoteId correctly. Interestingly, for my just create new user, remoteId was not set at all, authservice was set to 'gitlab' (in the database). Interestingly, authdata was set to the expected remoteId, so this what I did.

So
- Setting authdata in mattermost db to the id you have in authentic is what is required
- also you will need to set the authservice to 'gitlab'

When you did so, I got an error "Login failed because remote users are not allow to log in".

Then I tried nulling the password (since I assumed this is how they determined i'am a local user and this is the difference to the 'new user' I created before). Ended up with the error "We encountered an error trying to find the account by authentication type."

Currently, I cannot get past that for an existing user. If anybody has a hint, help me, i'am grateful.

**Update 1**
The code part relevant for me here is https://github.com/mattermost/mattermost/blob/a17c387ff24a93c215a727e87856717a04af0ecb/server/channels/app/user.go#L496
drills down to https://github.com/mattermost/mattermost/blob/a17c387ff24a93c215a727e87856717a04af0ecb/server/channels/store/sqlstore/user_store.go#L1255

So out of any reason, my authdata (id) or authservice does not match. Checking my data of the existing user (authdata: 7) and the new working one (authdata: 4) - I see no difference

```
select authdata,authservice from users where authdata = '4' or authdata = '7';
 authdata | authservice 
----------+-------------
 4        | gitlab
 7        | gitlab
---
```

**Update 2**
But then I checked the mattermost logs and found

```
We encountered an error trying to find the account by authentication type., failed to find User with authData=7 and authService=gitlab: sql: Scan error on column index 5, name "password": converting NULL to string is unsupported
```

So in the end, password is not allowed to be null, it needs to be an empty string and this was just a deserialization issue.

**Final guide for 'map to existing users' is:**

In Mattermost:
- set the field authdata to the ID your are going to expose in authentic in the id-scope.
- set the column 'authservice' to 'gitlab'
- ensure you update the password to an empty string (or you are considered a local user that is not allowed to login via external auth)

This query should get you started (for each user)

```sql
update users set password='',authservice='gitlab',authdata=<authentikId>,username='<authentikUsername>' where username='<curerntMattermostUsername>';
```

Thank you @feliscat for the heads up, pushed me to try again differently!

**Comment by 1stdevfriend** [comment]
> You can already use authentik for this. In the following i use the domain `sso.example.com` as the authentik instance.
> 
> First you need to create two property mappings (scope mapping; https://sso.example.com/if/admin/#/core/property-mappings):
> 
> ```
> Name: mattermostId
> Scope name: id
> Expression: return { "id": hash(request.user.id) }
> ```
> 
> and
> 
> ```
> Name: username
> Scope name: username
> Expression: return { "username": request.user.username }
> ```
> 
> Then you need to create a new application with oauth provider and assign the created property mappings to it: <img alt="image" width="473" src="https://user-images.githubusercontent.com/6099976/213440647-d40b878d-2563-48f8-860e-6e79836b5ef7.png">
> 
> As last you need to edit the mattermost config file (if you are using docker compose, the `config.json` file should be located at `/opt/mattermost/volumes/app/mattermost/config`). Replace the GitlabSettings section with the following:
> 
> "GitLabSettings": {
>         "Enable": true,
>         "Secret": "AUTHENTIK CLIENT SECRET",
>         "Id": "AUTHENTIK CLIENT ID",
>         "Scope": "",
>         "AuthEndpoint": "https://sso.example.com/application/o/authorize/",
>         "TokenEndpoint": "https://sso.example.com/application/o/token/",
>         "UserAPIEndpoint": "https://sso.example.com/application/o/userinfo/",
>         "DiscoveryEndpoint": "",
>         "ButtonText": "",
>         "ButtonColor": ""
>     },
> Then restart the mattermost container.
> 
> Please be aware that any existing user that has been authenticated with Gitlab or Email can not be re-used. You need to delete the user (or change the mail address) in order to sign-in with them.

Thank you so much for saving our time! <3
