### ISSUE TITLE
Celery CPU usage 100% on new install

### ISSUE THREAD

**Issue by traverseda** [goauthentik/authentik#4707]
**Describe the bug**

I'm using the attached docker-compose and env file (don't worry about the secrets in the env file).

[env.txt](https://github.com/goauthentik/authentik/files/10758594/env.txt)
[docker-compose.yml.txt](https://github.com/goauthentik/authentik/files/10758616/docker-compose.yml.txt)

**To Reproduce**

Run `docker-compose up` with the default configuration. Watch as celery uses 100% of a single CPU core. I've followed the setup guide from scratch twice to make sure I was getting as close as possible to a default install.

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
django.db.utils.InterfaceError: connection already closed
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.2.2
- Deployment: docker compose

**Comment by traverseda** [comment]
Any trouble reproducing this? I can't not reproduce it so far.

**Comment by traverseda** [comment]
`/tmp/celerybeat-schedule` is also not being created.

**Comment by marouamghar** [comment]
I tried it, it didn't fix it. I can hear the fans going out loud, and the cpu usage going through the roof.
One temporary fix is to limit the cpu usage of the server/worker, depending on how much it needs to still function. In my case, I'm able to fix it to 20%. Less and it starts hanging.

**Comment by billycao** [comment]
Also ran into this. I don't run a mission critical piece of infra, and downgrading to 2023.2 mitigated this issue for me for now, same as https://github.com/goauthentik/authentik/issues/3125#issuecomment-1467593856

My symptoms are identical to the original commenters in #3125: the python celery job is pinned at 100% CPU and the worker logs are filled with "Task Started" -> "Task Finished" for celery.

**Comment by electrofloat** [comment]
Any news on this one? I'm seeing the same on the worker container. Very frequent cpu spikes with the celery process using 100% of cpu.

**Comment by electrofloat** [comment]
It seems that the very frequent cpu usage spike is caused by: https://github.com/goauthentik/authentik/blob/main/lifecycle/ak#L83
If I add:
```
healthcheck:
      disable: true
```
to the compose file for the worker container, these frequent spikes are gone.
Now there are still other uses of celery which is scheduled like every 1 or 2 mins, but those seem more important like these ones:
```
scim_signal_direct
clean_temporary_users
save_reputation
clean_expired_models
```

@BeryJu Do you have any clues why the celery process uses so much cpu especially for the healthcheck? Maybe it could be replace with something not that demanding?

**Comment by BeryJu** [comment]
Interesting, I just noticed that the helm chart doesn't have liveness/readiness probes for the worker so that would probably explain why I'm not seeing these spikes. The healthcheck for celery could certainly run less often, as a broken worker does not directly cause any issues.

It seems the main reason why this healthcheck takes quite a bit of CPU (and also memory) is because it has to start a full python process with a lot of the authentik code imported, which takes quite some CPU

**Comment by marouamghar** [comment]
@BeryJu should we then remove the `depends_on` on the worker service in the compose file?

**Comment by uandreew** [comment]
I have the same problem, the whole server crashes because of authentik and its load is 100% CPU.

**Comment by sammcj** [comment]
The same problem here with 2023.6.1.

- docker-compose.
- minimal config (one domain forward auth).
- no errors or warnings in the logs.
