### ISSUE TITLE
Session duration not working correctly

### ISSUE THREAD

**Issue by christophdb** [goauthentik/authentik#4918]
**Describe the bug**
I changed the session duration of the default-authentication-login to 18 hours. Still, after a login the session is valid for 14 days.
For me, it looks like the session duration value is ignored.

**To Reproduce**
1. Go to 'Admin interface'
2. Click on 'Flows & Stages'
3. Edit 'default-authentication-login'
4. Change 'Session duration' to 'hours=18;minutes=0;seconds=0'
5. Logout & Login
6. Click on the settings-icon (“wheel”)
7. Check the session duration.

**Expected behavior**
I want to achieve, that every user has to authenticate once a day. Therefore, the session duration of 18 hours. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7803347/224706556-5ec007cf-9b0c-4aeb-9160-d6d779bfcc7b.png)
![image](https://user-images.githubusercontent.com/7803347/224707352-97c11b3c-672b-4355-bbb9-e603522217cb.png)

**Logs**
There are no logs.

**Version and Deployment (please complete the following information):**
 - authentik 2023.1.2
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
This is a purely cosmetical issue, because the user_login stage sets the expiry on the session after the login, but these session objects shown in the UI (which are _not_ the same as the actual sessions) are created when the login happens, so they didn't get the updated expiry. The actual expiry is always saved correctly into the session
