### ISSUE TITLE
Duplicate emails with different usernames allowed?

### ISSUE THREAD

**Issue by roney492** [goauthentik/authentik#5170]
**Describe your question/**
Duplicate emails with different usernames allowed? Shouldn't they be blocked, is there a condition or expression i can use to prevent enrolment of duplicate emails

**Relevant infos**
i.e. Version : 2023.3.1

**Comment by roney492** [comment]
Hi @tanberry 
Thanks for the clarification, please do let me know if you find anything on this.

**Comment by roney492** [comment]
Hi @tanberry ,
I have found a workaround for the same,
I removed the email field from the prompt, and in the stage section, I added an override for the email field being passed to the write stage.
Renamed Username as Email and added regex email validation for same.
So now am using email in the username field.

**Comment by tanberry** [comment]
Glad you found a workaround, @roney492. We will add some docs around how to validate for unique email addresses and [surface a message](https://goauthentik.io/docs/policies/expression#ak_messagemessage-str) if an attempt is made to use a non-unique one, but it might not be documented right-away; I am still learning this product. myself. ;-) 

I learned more this morning about how one can use an "[expression policy](https://goauthentik.io/docs/policies/expression)" to define a setting to check if there are dupes, then deny any request to use a non-unique value. There would be a bit of Python to write... I'll let you know when I have a PR for the docs around this, and feel free to jump in and add to PR if you like.

**Comment by GlenNicholls** [comment]
@tanberry Out of curiosity, why does authentik allow enrolling multiple usernames with the same email? Maybe I'm missing something, but this feels like an attack vector. At the very least, I would expect the default behavior of enrollment to require a unique username/email. Namely, if I allow username and email, my assumption is either can be used for authentication but neither should be allowed to overlap with another user; I assumed that email's core purpose was for account recovery.

I think this is a bug because if there isn't an email verification stage in enrollment, it would be possible for someone to make an account with an admin email. If they sign out and back in with that email, what determines which account they're logged into?

I did some experimenting with enrollment invites and was able to change the username and password of a superuser account when "Create users when required" enabled in the write stage due to the browser cache I believe. Even though the user was supposed to be deactivated until email confirmation and the group was non-superuser, the superuser account disappeared and my new account had admin access without verifying the email... I also made a few different accounts with the same email and it consistently logged me into the first account (`tmp` instead of `tmp2`) when I authenticated with email and had all accounts set with the same password. So yeah, not entirely sure what to think here as `non-unique email addresses are allowed, on purpose, for diff user names` feels like a security bug, not a feature.

**Comment by BeryJu** [comment]
For context, the reason why emails are not unique out of the box with authentik is due to Django's defaults, where email addresses are not defined as unique. Retroactively adding uniqueness is always a challenge, especially with emails as there's no automated resolution to dealing with a duplicate email address.

There are two ways to change this behaviour, one is to use a policy to set the username to the email address if your usecase does not require a separate username. The other option is to use a policy to check for uniqueness manually. We will add examples for both of those policies and how to use them to the docs

**Comment by BeryJu** [comment]
https://docs.goauthentik.io/docs/policies/working_with_policies/unique_email
