### ISSUE TITLE
AdminUI: Display of grouping for Policies / Property Mappings with strange behavior

### ISSUE THREAD

**Issue by BobSilent** [goauthentik/authentik#5336]
The grouping in the table seems to be rather random.
Especially when you have more entries than can be displayed on one page (btw. it would be cool to select the number of items to be displayed on a page dynamically), the entries are spread over several pages.

Example
page 1:
![image](https://user-images.githubusercontent.com/13506173/233589914-effe5c79-43a8-4c37-85e8-4c61c887c6a3.png)

and although it looks like the group "LDAP Property Mappings" or "SAML Mappings" is completely displayed on page 1, you still get entries on page 2
![image](https://user-images.githubusercontent.com/13506173/233589955-a4e0b91d-f655-4da2-9e27-f99b2b196b8a.png)

In my opinion, the grouping should simply be removed, since it doesn't really add any value. 
The group membership is shown as a separate column in the table anyway.

It gets even more strange with the "policies", since the grouping is not shown from page two
![image](https://user-images.githubusercontent.com/13506173/233590298-c357e834-aa54-404c-9ec8-8c704f7a7db9.png)

I think this issue will also be in Flows, Stages, Prompts UI (but this I did not test)

**Version and Deployment:**
 - authentik version: 2023.4.1
 - Deployment: docker-compose

**Comment by BeryJu** [comment]
The reason for the inconsistency is that the pagination is done server-side and the grouping is done client-side. The only ordering is done by the name. The grouping can't easily be done server-side as the different types of the policies/property mappings are subclasses so there's no database column we can use for sorting the results.

The reason why the second policies page doesn't have any grouping is because the grouping only happens if there's multiple different types of objects

**Comment by BobSilent** [comment]
So, in my opinion, the grouping should simply be removed, since it doesn't really add any value and a dedicated row with the information also exists
