### ISSUE TITLE
Support for more Invitation events on Event Matcher Policies

### ISSUE THREAD

**Issue by pinarruiz** [goauthentik/authentik#5773]
**Is your feature request related to a problem? Please describe.**
In an organization having control over when Invitations are created and/or expired would be great, this way administrators could set up alarms for when a policy is created, or add webhooks using the event system. we already have the Invite used event, so this will extend the functionality.

**Describe the solution you'd like**
Implement Event Matcher Policy actions for:

- Invite Created.
- Invite Expired.
- Invite Deleted.

**Describe alternatives you've considered**
Using the Authentik API is a possibility, but setting up a webhook or automatic emails seems cleaner.

**Comment by BeryJu** [comment]
@pinarruiz we don't currently have a distinction in the events whether an invitation has expired or was deleted (since the expiry action for an invitation is to delete it), but I think in general it makes sense to add a field to the event matcher policy to filter based on database models, which would also work for this

**Comment by pinarruiz** [comment]
Hello @BeryJu that sounds good, the filter on database models would work on other models, like flows or stages? that would allow to expand the event system greatly.

**Comment by BeryJu** [comment]
this was added with #5802, and yes the filter works on any model
