### ISSUE TITLE
maybe bug: field username type username doesn't check duplicates or not as expected user12 and User12 are different.

### ISSUE THREAD

**Issue by pbvdven** [goauthentik/authentik#5844]
**Describe the bug**
Enrolment field username type username wont check on duplicates 

**To Reproduce**

Create user enrolment flow "need a new account? sign up"
make sure the type of the username field is set to username
make sure user12 exists 
now user12 already exists but when a new users creates User12 there is warning that user12 already exists and the user gets created.

**Expected behavior**
Warning username is taken choose other

**Screenshots**
![image](https://github.com/goauthentik/authentik/assets/39600990/64605d7c-62b2-4bd3-9a17-e07111e59f90)
![image](https://github.com/goauthentik/authentik/assets/39600990/9a4f23dc-a2e1-4658-ad63-8fe4ec64207e)
![image](https://github.com/goauthentik/authentik/assets/39600990/f850fd34-5927-493d-8412-88c26b134b99)
![image](https://github.com/goauthentik/authentik/assets/39600990/686b8ac2-9605-4dac-bf61-ef6dc3165963)
![image](https://github.com/goauthentik/authentik/assets/39600990/88904ee2-5666-4b61-bd98-18fa6ea2b6d3)
![image](https://github.com/goauthentik/authentik/assets/39600990/d62c4461-b7a3-4e9f-a167-bd22cb029d12)
![image](https://github.com/goauthentik/authentik/assets/39600990/a637ca27-6043-4ca7-8396-a0f658d9472a)

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2023.5.3]
-   Deployment: docker-compose

**Additional context**

**Comment by larsl-net** [comment]
Hey @pbvdven ,

I have built a `Expression Policy` which can prevent this.

```python
if ak_user_by(username__iexact=context['prompt_data']['username']) is None:
  return True
else:
  ak_message("Username is already taken.")
  return False
```

But the format of the error message are different with this way.
Username of the existing user: `Test`

The official username field check
![image](https://github.com/goauthentik/authentik/assets/33843261/e97ff182-49ff-4e1e-9df6-27f4f0d1dc17)

The Expression policy to additional match Case-Insensitive
![image](https://github.com/goauthentik/authentik/assets/33843261/4d0d8da5-16e3-459b-8f78-01488f29f04c)

Theoretically you could change the type of the username field to text then the difference in the error message would disappear (only the second prompt).

The username field should be changeable to Case-Insensitive, because I don't know if there can be problems at other places.

**Comment by asifbacchus** [comment]
Just noticed this issue also. Potentially a huge problem that has been labelled `wontfix`. Once the second user signs up with the same username, neither account can log in via username due to the ambiguity. At the very least, perhaps we should add the policy @larsl-net created to the documentation so others can work-around this issue?

**Comment by nusol-sc** [comment]
We just ran into this exact problem. We are using Authentik 2024.4.2. We pre-created a bunch of users, but because the case of the email addresses didn't always match due to differing case (which wasn't even consistent across the different users), we end up with duplicate users. Obviously, problems ensued.

We used lowercase for the usernames because, well, under NO circumstances should a username or email address be case sensitive. Yahoo made the same mistake in the late 90's with case sensitive email addresses. Very bad idea, and it was mind-boggling that a company like Yahoo would make such a blunder.

I am VERY concerned by asifbacchus's mention that the issue was labelled "wontfix". I'm genuinely eager to hear arguments for why a username/email address should be treated as case sensitive. This will require the implementation of unnecessary hacks and workarounds to overcome a self-created problem.

I guess I will attempt the aforementioned expression policy workaround. Ugh. *double facepalm*
