### ISSUE TITLE
GET /api/v3/flows/executor/default-password-change/ - Error when trying to change password for LDAP user

### ISSUE THREAD

**Issue by v1k7g85** [goauthentik/authentik#6466]
**Describe the bug**
The error occurs when the option "User password writeback" is enabled in the LDAP Source configuration. When trying to change the password in the user profile, an error "Something went wrong! Please try again later" apearce

**To Reproduce**
1. Go to 'Federation & Social login'
2. Set option 'User password writeback' in LDAP source configuration
3. Go to 'Directory/Users'
4. Click "Impersonate' next to the user
5. Select "Settings/Chancge password'
6. Write password
7. Click 'Continue'
8. See error

**Expected behavior**
Password changed

**Screenshots**

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 298, in get
    stage_response = self.current_stage_view.get(request, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/user_write/stage.py", line 154, in get
    self.update_user(user)
  File "/authentik/stages/user_write/stage.py", line 100, in update_user
    setter(value)
  File "/authentik/core/models.py", line 197, in set_password
    password_changed.send(sender=self, user=self, password=raw_password)
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/signals.py", line 62, in ldap_sync_password
    changer.change_password(user, password)
  File "/authentik/sources/ldap/password.py", line 96, in change_password
    self._connection.extend.standard.modify_password(user_dn, new_password=password)
  File "/usr/local/lib/python3.11/site-packages/ldap3/extend/__init__.py", line 82, in modify_password
    controls).send()
              ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ldap3/extend/operation.py", line 51, in send
    raise LDAPExtensionError('extension not in DSA list of supported extensions')
ldap3.core.exceptions.LDAPExtensionError: extension not in DSA list of supported extensions
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2023.6.0
- Deployment: helm

**Additional context**
No additional context

**Comment by esackbauer** [comment]
Go back to 2023.5.5, that worked for me.

**Comment by BeryJu** [comment]
@v1k7g85 which LDAP server are you using? I haven't seen this error message before

**Comment by v1k7g85** [comment]
@BeryJu i'm using Active Directory on Windows Server 2019

**Comment by v1k7g85** [comment]
I got exactly the same error on 2023.8.3. There may be a problem with setting permissions on the Active Directory side. I tried many different configurations from the internet, but nothing helped. If anyone has successful experience integrating authentik with AD Windows 2019, please share.

**Comment by esackbauer** [comment]
@v1k7g85 

I don't have this error in 2023.8.3. However I my AD is Windows Server 2016, but I guess this makes no difference.
I would strongly suggest you redo everything which is mentioned for AD connection, including the AD user needed for AD modifications as per documentation, it works for me.
https://goauthentik.io/integrations/sources/active-directory/

**Comment by iRaven4522** [comment]
Same issue here, everything else related to AD works for me (users/groups sync, authenticating, etc) but only password changes don't work. When testing with a user account on the default-password-change flow I get a 405 returned. The service account I'm using has all the necessary delegated permissions outlined in the docs.

**Comment by paulogorgias** [comment]
I am facing the same issue. Does anyone know how to fix this, or have any idea how I could configure Authentik to work with Active Directory for resetting passwords?

**Comment by dukz** [comment]
I'm having the same issue. When I have the user set as a member of domain admin, I have the same stack trace as the one above with the message "extension not in DSA list of supported extensions"

When I do follow the one outlined in the configuration page where the user is delegated access, I have a different error trace. See below.

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 290, in get
    stage_response = self.current_stage_view.dispatch(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/stages/user_write/stage.py", line 163, in dispatch
    self.update_user(user)
  File "/authentik/stages/user_write/stage.py", line 109, in update_user
    setter(value)
  File "/authentik/core/models.py", line 271, in set_password
    password_changed.send(sender=self, user=self, password=raw_password)
  File "/ak-root/venv/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/sources/ldap/signals.py", line 77, in ldap_sync_password
    ).set_user(user).save()
                     ^^^^^^
  File "/authentik/events/models.py", line 287, in save
    super().save(*args, **kwargs)
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/ak-root/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/django_prometheus/db/common.py", line 69, in execute
    return super().execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: unsupported Unicode escape sequence
LINE 1: ...ration_error', 'authentik.sources.ldap.signals',  E'{"messag...
                                                             ^
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: ...oblem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\u0000...
```

Going through the logs inside of docker yields me this error message:

```
Failed to change password in LDAP source due to remote error: 50, 00000005: SecErr: DSID-031A11EF, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\u0000, insufficientAccessRights
```

Seems like something else needs to be done in AD to delegate properly.

My environment is:
* Windows Server 2022 21H2
* Domain Fucntional Level is Windows Server 2016

**Comment by dukz** [comment]
OK. I think I might have figured it out.

I've been testing the reset password on a user that's part of the Domain Admins, which is probably why it's throwing this error. 

I created a regular user that's only part of the "Domain Users" group, and was able to reset that users password properly.

**Comment by D3B453R** [comment]
Sorry, my bad, just checked my config and I was missing the "(&" at the beginning of my userobjectfilter under ldap source. Corrected it to "(&(objectClass=user)(!objectClass=Computer)))" and now everything works as expected. :)

**Comment by pubyun** [comment]
> Sorry, my bad, just checked my config and I was missing the "(&" at the beginning of my userobjectfilter under ldap source. Corrected it to "(&(objectClass=user)(!objectClass=Computer)))" and now everything works as expected. :)

after i set user filter to "(&(objectClass=user)(!(objectClass=computer)))", i got same message  “raise LDAPExtensionError('extension not in DSA list of supported extensions')”

**Comment by acausbu419** [comment]
I wanted to share a solution I ran into with an issue I was having with the password writeback feature.

We have user accounts set up in active directory where the domain suffix has been changed from like say ad.example.net to example.com. I'm not sure why that is the case, but it's actually what kind of led me to this software because of the property mappings feature.

At first I could reset passwords in the admin interface from the users section, so I did not think I had a mapping issue with this feature, but when attempting recovery flows I would get:

`DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: ...oblem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\u0000...`

Thrown in the events. I knew I did not have permission issues, so I was kind of grasping at straws, and I introduced that same alternateSuffix mapping into my lab on a domain user account, and suddenly I could not reset passwords anymore in that environment either.

Ultimately I made a rough ldap property mapping to take the given upn (to preserve the username field as our samaccountnames also differ) and store it in authentik where it would find a match based on the expected upn. This got me the expected result and my password recovery flow started working.

LDAP Property Mapping

Object field - attributes.upn

`temp = list_flatten(ldap.get('userPrincipalName'))
new_domain = "ad.example.net"

# Split the email address into username and domain
temp, domain = temp.split("@")

# Create the new email address with the updated domain
new_email = f"{temp}@{new_domain}"

return new_email  # Output: upn@ad.example.net`

There's probably a simpler way to go about the result, but it got me there.

**Comment by slevin22** [comment]
> I wanted to share a solution I ran into with an issue I was having with the password writeback feature.
> 
> We have user accounts set up in active directory where the domain suffix has been changed from like say ad.example.net to example.com. I'm not sure why that is the case, but it's actually what kind of led me to this software because of the property mappings feature.
> 
> At first I could reset passwords in the admin interface from the users section, so I did not think I had a mapping issue with this feature, but when attempting recovery flows I would get:
> 
> `DETAIL: \u0000 cannot be converted to text. CONTEXT: JSON data, line 1: ...oblem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\u0000...`
> 
> Thrown in the events. I knew I did not have permission issues, so I was kind of grasping at straws, and I introduced that same alternateSuffix mapping into my lab on a domain user account, and suddenly I could not reset passwords anymore in that environment either.
> 
> Ultimately I made a rough ldap property mapping to take the given upn (to preserve the username field as our samaccountnames also differ) and store it in authentik where it would find a match based on the expected upn. This got me the expected result and my password recovery flow started working.
> 
> LDAP Property Mapping
> 
> Object field - attributes.upn
> 
> `temp = list_flatten(ldap.get('userPrincipalName')) new_domain = "ad.example.net"
> 
> # Split the email address into username and domain
> temp, domain = temp.split("@")
> 
> # Create the new email address with the updated domain
> new_email = f"{temp}@{new_domain}"
> 
> return new_email # Output: [upn@ad.example.net](mailto:upn@ad.example.net)`
> 
> There's probably a simpler way to go about the result, but it got me there.

Unfortunately this didn't solve it for me. I'm still getting "extension not in DSA list of supported extensions" with 2024.6, with the mapping generating upns, with user filter set to "(&(objectClass=user)(!(objectClass=computer)))", and both with the authentik bind user in domain admins and with the permissions set directly on that user.

Anybody have any ideas? :disappointed:

**Comment by acausbu419** [comment]
I barely know what I'm doing in here as I'm still learning this solution, so please just treat these as rambling suggestions at best.

I have a very similar issue with one ldap source, but I haven't been able to fully narrow down the issue.

In my case, the ldap source is a child active directory domain. If I enable logging, and set my source to ldaps://dc.ad.example.com:636 and see the request come in as searching for the user against the root domain and not the child domain, or searching example.com instead of ad.example.com, sending the request to a root dc, and then the connection being reset, making me wonder if my issue is with the way the search base is being set on the search. 

I only get the error you refer to when I set the port to like 3269 for the gc port, the request goes another route, where my dc performs the lookup, and then responds that the task will not be completed (the actual password writeback) because of the usage of a GC port in the event logs on the DC after enabling additional directory service logging. If I switch to ldaps://636 though I get a `ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, socket is not open` - which sort of matches how I saw it wireshark and event logs where this connection was reset, but I haven't been able to resolve that issue since that's the request that seems to go to the root domain prior to being reset. That is to say that if you review your ldap source and enable additional logging if you need to do that like I did, you may get more info relevant to your issue.

I haven't been able to return to this to look into it further on the settings side, but the issue is still present on 2024.6 for me as well, but only on an ldap source that is a child AD domain. My lab server is set up with the same source settings, but the DC is a root DC and I have no issues writing passwords back in that context after the upn remapping I did on my last post.

Directory service logging enabled on child AD DC:

New-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Diagnostics' -Name "16 LDAP Interface Events" -Value 2 -PropertyType DWORD -Force

New-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Diagnostics' -Name "15 Field Engineering" -Value 5 -PropertyType DWORD -Force

**Comment by slevin22** [comment]
Thank you so much for the response! I have no idea if this is what actually fixed it or what, but after changing my ldap connections to use SSL (which your discussion of ports gave me the idea to do) I'm now only getting errors when trying to change domain admin passwords, and it's the "DETAIL:  \u0000 cannot be converted to text." error.

**Comment by acausbu419** [comment]
Ah I can answer that part a little more confidently, but domain admins have inheritance disabled on their account, which basically turns these into denied requests. I know of no way to work around that. If you change the context on a domain admin account to inherit permissions, I believe you have other concerns there, but that actually resets every 15 minutes, so I wouldn't recommend it.

**Comment by acausbu419** [comment]
And to your other point I believe it's covered that ldap is not allowed for password writeback, and that ldaps is a requirement, so I think that tracks with what you had changed as well on your SSL settings.

**Comment by slevin22** [comment]
That makes sense. Well again, thank you very much!
