### ISSUE TITLE
docker 2023.8.0 - login without password, just valid username

### ISSUE THREAD

**Issue by segro21** [goauthentik/authentik#6673]
i just updated my docker test install and noticed, that I can login with a valid username but without a password from any device...

akadmin is valid ..
notauser is not valid and no login..

**Comment by esackbauer** [comment]
I can confirm this!
Do you have LDAP/AD configured as federation/AD sync?

**Comment by BeryJu** [comment]
> I can confirm this! Do you have LDAP/AD configured as federation/AD sync?
> 
> How could this pass quality checks??

This error only happens when upgrading from certain versions, specifically when upgrading from installs that were installed before https://github.com/goauthentik/authentik/commit/39d08933034fe031ed20a30b6e1aedfd5eb5fc60 which was first released in 2023.3.0. As much as I would like to, testing 5+ versions back, automatically, is not really possible

**Comment by segro21** [comment]
@esackbauer no, this is not connected to AD/ldap, just local users
and @BeryJu : the version was just the last one: 2023.6 (running) and I simply download the compose + docker compose up -d after that... perhaps I hat version 2023.3.x running  months before, but not yesterday

**Comment by BeryJu** [comment]
@segro21 yeah the important part is whether the install has been upgraded from 2023.3.0 through any release to 2023.8, but 2023.8.1 will be released shortly that fixes the issue
