### ISSUE TITLE
Google Idp-configuration not working

### ISSUE THREAD

**Issue by doei135** [goauthentik/authentik#7115]
**Describe your question**
recieving emails with policy_exception, did i configured anything wrong?
The User gets created, but a policy_exception is send via email

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8
-   Deployment: docker-compose
- Authentik, behind a traefik-reverse-proxy

**Relevant infos**
Configured the Google-Auth like described in the Docu: https://goauthentik.io/integrations/sources/google/#username-mapping

Added the Policy to the "default-source-enrollment"-Flow

|||
|---|---|
|Name: | Google Username |
|Order: | 0 |
|Timeout: | 30 |

Expression:
```
email = request.context["prompt_data"]["email"]
request.context["prompt_data"]["username"] = email.split("@")[0]
return False
```

the Following error gets send via email if a user logins in via google:

---

authentik Notification: policy_exception
Traceback (most recent call last): File "Google Username", line 5, in <module> File "Google Username", line 2, in handler builtins.KeyError: 'prompt_data'

| Additional Information | |
|---|---|
|user_email | test@example.com
|user_username | testaccount
|event_user_email | test@example.com
|event_user_username | testaccount
|message | Traceback (most recent call last): File "Google Username", line 5, in <module> File "Google Username", line 2, in handler builtins.KeyError: 'prompt_data'
|policy_uuid | XXXXXXXXXXX

**Comment by BeryJu** [comment]
Depending on the authentik version, it is possible that the policy is executed both when the initial flow plan is created as well as when the user gets to the stage. Since there's no prompt data available when the flow plan is created, the policy will fail. You can either check if the "prompt_data" key exists, or make sure the `Evaluate when flow is planned` option on the stage binding is disabled.
