### ISSUE TITLE
Virtual Group gidNumber different than the `uidNumber` on a user

### ISSUE THREAD

**Issue by dkowis** [goauthentik/authentik#7524]
**Describe the bug**

Context: I'm prototyping using goAuthentik for things instead of openldap. Since I've got an existing OpenLDAP setup, I need to specify my UID/GIDs so that they'll line up with the existing ones, else I'll have to do a whole lot of chowning, which I'd rather not do.

So I've created a user: dkowis and set the uidNumber custom
![image](https://github.com/goauthentik/authentik/assets/28048/b2822408-b9a6-4bd4-95ae-c46bb3cd006f)

However the LDAP client shows a virtual group with a different gidNumber:
![image](https://github.com/goauthentik/authentik/assets/28048/895e348e-a316-41dd-b103-577e1e293da4)

the user data is correct:
![image](https://github.com/goauthentik/authentik/assets/28048/f85d203a-0d32-4bcd-99ff-4d99f4347947)

**To Reproduce**

1. Set up goauthentik, and an LDAP outpost
2. create a user (don't set uidNumber in the user settings when you create it)
3. check LDAP, note that the uidNumber isn't what you want it to be
4. define a uidNumber for what you want it to be
5. see that LDAP shows the right uidNumber
6. check the virtual group created, and see that the gidNumber is wrong :(

**Expected behavior**
The gidNumber to match what the docs say, which matches the uidNumber of my user.

**Screenshots**
Screenshots are inline

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment:**

-   authentik version: 2023.10.3 (I'll update and check again, confirmed still same behavior on 2023.10.3)
-   Deployment: docker-compose

**Additional context**

**Comment by LincolnBryant** [comment]
:+1: I am also interested in a solution to this problem.

**Comment by Ra72xx** [comment]
I have this problem since I started using Authentik about a year ago (?). Virtual groups in LDAP never returned a useful gid number. Somehow it looks as if the virtual group gid is incremented from the correct value. As I have only a few users needing this gid, I manually created "real" groups for them.
I imported users and groups from a 389DS LDAP server (after first using 389DS as a data source as a step for the complete migration), maybe something went wrong here.
