### ISSUE TITLE
Persistent Alert | A newer version of the frontend is available.

### ISSUE THREAD

**Issue by bhenchodgroup** [goauthentik/authentik#773]
After upgrading to V. 2021.4.4 a persistent alert message appears stating "A newer version of the frontend is available". Clicking the reload button causes a 404 error.

**Comment by BeryJu** [comment]
Thanks for the report! The alert is shown when the version of the frontend doesn't match the version of the backend, which can happen since the frontend is cached aggressively.

When you click the reload button, what does the URL change to? The reload button should just reload the current page to clear the cache. You can also press Control+Shift+R to clear the cache and reload and get rid of the banner.

**Comment by BhenchodGroup** [comment]
Please see the attached screenshot of the console.

https://i.bhenchod.io/opera_TBO7pd7S7R.png

**Comment by BeryJu** [comment]
It's a bit odd that its failing to load the sourcemap, but that doesn't have any impact on the functionality.

What URL are you sent to when you click the reload button?

**Comment by BhenchodGroup** [comment]
It actually looks like the page just refreshes, but the alert is still there.

**Comment by BeryJu** [comment]
https://support.cloudflare.com/hc/en-us/articles/115003206852

`vary — Cloudflare doesn't consider vary values when making caching decisions.`
