### ISSUE TITLE
Consider switching to smaller images for docker + rootless

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#840]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
When running the default docker-compose file, Authentik is using bigger docker base images. However. PostgreSQL is running fine with the alpine version of PostgreSQL 12. It saves a lot of space and is safer to use. (less is more!)
Also, the python base image is also available with an alpine tag. (not tested)
For more security and more disk space, please consider switching the images. For even more security, make it possible to run the containers without root. The current static container won't run without it, because port 80.
Most of my container are using the `user:` value.

**Describe alternatives you've considered**
Using smaller images.

**Additional context**
none.

**Comment by BeryJu** [comment]
> When running the default docker-compose file, Authentik is using bigger docker base images. However. PostgreSQL is running fine with the alpine version of PostgreSQL 12. It saves a lot of space and is safer to use. (less is more!)

Both postgres and redis I can replace with the alpine version, this does make sense (I though the default images for both of those was alpine by default but apparently not)

> Also, the python base image is also available with an alpine tag. (not tested)

This is a conscious decision, as on alpine many of the python wheels don't exist, since they were compiled for libc. This usually results in a bigger image that takes longer to build with alpine.

> For even more security, make it possible to run the containers without root. The current static container won't run without it, because port 80.

The static container will be removed in the next release, and the server/worker containers already run as non-root.
