### ISSUE TITLE
Cloudflare Access Guide

### ISSUE THREAD

**Issue by 4d62ext** [goauthentik/authentik#9710]
**Is your feature request related to a problem? Please describe.**
A part of my selfhosted applications are running on Cloudflare Tunnels which allow easy protection with Access. Unfortunately, Authentik does not provide a guide on how to setup an "application" for CF Access.

**Describe the solution you'd like**
Documentation created. I set it up myself and I wouldn't mind opening a pull request with my implementation. I'll probably create one in a few hours. 

**Describe alternatives you've considered**
Proxying all applications with a reverse proxy. It's just not possible 100% of the time in certain use cases

**Additional context**

**Comment by gitchrishan** [comment]
assuming you have a reverse proxy installed already that is exposed to your cloudflare tunnel and have authentik working locally, you would use the local proxy url of your application in the host section of cf tunnels. so instead of exposing the docker container directly, you would use the mydockerinstance.local.mydomain.com if that makes sense
