### ISSUE TITLE
One login to rule (access) them all!

### ISSUE THREAD

**Issue by YouveGotMeowxy** [goauthentik/authentik#9725]
**Describe your question**

Can someone please have a look at the question here: https://discord.com/channels/809154715984199690/1239689758259806318

as looking through the support questions there, seems non-existent, so I'm asking again here because I need to get this going as soon as possible and I have some time to work on it tonight.

thanks in advance!

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.4.2
-   Deployment: official docker image + SWAG, in docker swarm.

**Comment by ksaadDE** [comment]
Can you copy paste the discord question or take a screenshot?

**Comment by YouveGotMeowxy** [comment]
> Can you copy paste the discord question or take a screenshot?

![image](https://github.com/goauthentik/authentik/assets/39491297/02285523-cf95-4034-93fd-294195bd4cee)

> Furthermore questions seem to be better suited in discussions.

![image](https://github.com/goauthentik/authentik/assets/39491297/0db2b637-0cd0-4209-ae2a-3b3c438dd224)

**Comment by ksaadDE** [comment]
@YouveGotMeowxy my bad I did not think of the form, that posts questions as issues.

Can you by chance post the attatched img link too? Or at best the image itself.

**Comment by BeryJu** [comment]
The difference is better explained here: https://docs.goauthentik.io/docs/providers/proxy/forward_auth#forward-auth-modes

the tl;dr being that for domain-level forward auth you only create on app in authentik which will give you the same result as with authelia, however due to how the policy/authz system works, this also means that you'll only be able to grant/deny access for that entire domain. The other option would be to automate the applications/providers for each subdomain using the API https://docs.goauthentik.io/developer-docs/api/reference/authentik
