### ISSUE TITLE
fail2ban-like setup

### ISSUE THREAD

**Issue by Akruidenberg** [goauthentik/authentik#974]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Authelia has an option to add Fail2ban to the login dialog. It would be nice to have this feature also with Authentik

**Describe alternatives you've considered**
Make to possible to integrate Fail2ban with Authentik

**Additional context**
Authentik version: 2021.5.4
Docker compose

**Comment by BeryJu** [comment]
While I don't know how the authelia fail2ban integration works, you can implement something similar using a Reputation Policy, as on each failed login attempt the reputation for both the IP and the username is decreased. You can create a Reputation policy that requires a certain score, bind it to a flow, and that would probably have the same outcome.

**Comment by asifbacchus** [comment]
@BeryJu, I tried the reputation idea and while I like the theory, it doesn't seem to actually block things at least the way that something like fail2ban would. If I make a user and purposely enter a bunch of wrong passwords, authentik will correctly say access denied. However, if I reload the page or close the browser and start again, I can go ahead and try logging in until I hit the threshold again... then repeat again and again. In addition, my IP is never blocked.

When I check the reputation policies under customization, they are sometimes updated and sometimes have reverted to a point in the past. Obviously, this seems to be the root of the problem. Is there a way to check this?

Also, just to confirm: If I set a reputation policy (say for username checking) and I check "Check Username" then set the threshold at -5 that means the policy will return *true* for any value *above* -5, right? So it will only fail after 6 invalid attempts with the same username?

**Comment by BeryJu** [comment]
I should have explained a bit better, my bad.

@asifbacchus what you're running into is actually a different mechanism, which is the Password stage's `Failed attempts before cancel`. This configures, as you've already noticed, how many times you can attempt to enter a password before the flow is cancelled.

With a ReputationPolicy, you can either assign it to a stage (I do this to conditionally require a captcha), or apply it to a flow (which will cause the entire flow to not be applicable, just make sure to have a backdoor to get in).

To use the policy with a stage, make sure these flags are set on the stage binding:

![image](https://user-images.githubusercontent.com/1932513/122642928-317d3000-d10d-11eb-98fd-351406bfc2d0.png)

As otherwise, authentik will cache the result of the policy, and cache the entire flow.


The other issue with the inconsistent values is a bit odd, do you have multiple servers running? On each failed login (with correct username and password) OR failed identification (username that doesn't exist), the score for that IP and entered username is lowered by 1. This is "saved" in the Redis cache, cause it is a lot faster than saving it to the database. 
Every 5 minutes a background task runs on the worker container, which saves the current values to the database. The actual policies check against the cache, but the UI shows the currently saved values in the database (now that I'm typing this out, I am realising the issue with this)

**Comment by asifbacchus** [comment]
Thanks for clearing up the confusion, makes sense now! So I cannot apply a Reputation Policy directly to an application? That is what I'm doing and, if that's wrong, it explains everything 😛

**Comment by BeryJu** [comment]
Currently the policy engine always caches, unless explicitly told not to. Both when listing applications and checking access, this cache is used. In the current version, you could of course just use a special flow for authorisation, that has the policy bound as above, and can conditionally deny the authorisation process.

I'll look into making this easier in the next version, just having a per-policy toggle whether or not to cache the result.

This would also remove the duplicate flag from the flow stage bindings (since that's essentially what the re-evaluate flag does, run a PolicyEngine without cache)

**Comment by asifbacchus** [comment]
That's what I've decided to do -- make a new authorization flow with the policies applied and leave the defaults alone. I think it should work. I agree that anything that makes it easier is welcome since this is one of the most confusing aspects of any system such as authentik. Thanks again for taking the time to get back to me.

**Comment by asifbacchus** [comment]
Possibly stupid follow up question: authentik itself uses the *default-autentication-flow*, correct? So if I were to apply any Reputation Policies to that flow, I could lock myself out of authentik as well, right? In that case, is there a way to add a time delay? Like have the IP/username only blocked for say 30 minutes?

Conversely, if authentik uses a totally different flow then how do I protect against attacks on authentik itself?

Thanks!

**Comment by BeryJu** [comment]
> Possibly stupid follow up question: authentik itself uses the _default-autentication-flow_, correct? So if I were to apply any Reputation Policies to that flow, I could lock myself out of authentik as well, right? In that case, is there a way to add a time delay? Like have the IP/username only blocked for say 30 minutes?
> 

authentik uses whichever flow is configured as default in the tenant. Currently, the IP and Username reputation is stored in cache for 5 minutes, after which it is essentially reset. In the next release I'll fix the resetting, as it should just default to the latest value from the database instead. 

For the time-based lockout, I could check the TTL of the cache entry, and check if its under a specified threshold

**Comment by asifbacchus** [comment]
Ah, fair enough. I'll have to take a look at those tenant settings more carefully. So, if a user is locked out, it resets in 5 minutes and they can try again? Is that right?

Also, yes, I think having a configurable threshold would be an awesome enhancement. Thanks again for answering all my questions!

**Comment by BeryJu** [comment]
> So, if a user is locked out, it resets in 5 minutes and they can try again? Is that right?

Indeed, same for a locked IP (also make sure to bind the reputation policy with a re-evaluation flag to ensure its not cached, as the policies are cached for longer)

> Also, yes, I think having a configurable threshold would be an awesome enhancement.

I've been thinking about a good way to implement this, it would only really work as a global setting, since the reputations are saved globally and not per policy.

**Comment by asifbacchus** [comment]
I would think globally is just fine. Usually something like this makes more sense globally anyways, or at least per-tenant. Personally, I use this to avoid scripts/bots so a global setting is a huge step in the right direction for me.
