### ISSUE TITLE
Deadlock reported by database

### ISSUE THREAD

**Issue by szinn** [goauthentik/authentik#9766]
**Describe the bug**

message":"deadlock detected","detail":"Process 126404 waits for ShareLock on transaction 915753; blocked by process 126403.\nProcess 126403 waits for ShareLock on transaction 915756; blocked by process 126404.\nProcess 126404: SELECT \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"description\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"icon\" FROM \"authentik_stages_authenticator_webauthn_webauthndevicetype\" WHERE \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\" = '39a5647e1853446ca1f6a79bae9f5bc7'::uuid LIMIT 21 FOR UPDATE\nProcess 126403: SELECT \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"description\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"icon\" FROM \"authentik_stages_authenticator_webauthn_webauthndevicetype\" WHERE \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\" = '08987058cadc4b81b6e130de50dcbe96'::uuid LIMIT 21 FOR UPDATE","hint":"See server log for query details.","context":"while locking tuple (3,1) in relation \"authentik_stages_authenticator_webauthn_webauthndevicetype\"","query":"SELECT \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"description\", \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"icon\" FROM \"authentik_stages_authenticator_webauthn_webauthndevicetype\" WHERE \"authentik_stages_authenticator_webauthn_webauthndevicetype\".\"aaguid\" = '39a5647e1853446ca1f6a79bae9f5bc7'::uuid LIMIT 21 FOR UPDATE","backend_type":"client backend","query_id":"0"}}

**To Reproduce**

No user interaction required

**Expected behavior**

No deadlocks

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

2024.4.2

**Additional context**

**Comment by excaliburzarau** [comment]
Hello,

I had a similar issue.
I was trying to deploy a clean install of authentik and i was having this error.

I spent a couple of days trying to actually understand the issue but without success.

I was having issues reporting that the initial-setup page was not found and after a couple of changes i was able to get to the page to create the akadmin user but every time that i set a password i got another error.

![Sem título](https://github.com/goauthentik/authentik/assets/132749063/35f05a18-8cdd-43ad-b5ee-84acf302e45e)

![image](https://github.com/goauthentik/authentik/assets/132749063/e7e0fbad-5ef9-40c0-971f-db0e6601683d)

The workaround i found it is quite peculiar but it worked.

![image](https://github.com/goauthentik/authentik/assets/132749063/0e2e853d-d93d-44b5-9e4c-32b7fec1efd1)

I used the docker images as seen on the image above.

Started with the first release 2023.1.1 which worked without any issue.
I then used the image 2023.8.1 which is required before updating to the later version 2023.10.2 and where i believe the login has an issue as it did not require a password when login. This was reported on the post below.

 [https://github.com/goauthentik/authentik/security/advisories/GHSA-rjvp-29xq-f62w](url). 

This issue was resolved on the version 2013.10.2.
I then used the version of 2024.2.0 which also worked and then proceeded to update it to the latest version 2024.4.2

Best Regards

**Comment by info-path** [comment]
> Started with the first release 2023.1.1 which worked without any issue. I then used the image 2023.8.1 which is required before updating to the later version 2023.10.2 and where i believe the login has an issue as it did not require a password when login. This was reported on the post below.
> 
> [https://github.com/goauthentik/authentik/security/advisories/GHSA-rjvp-29xq-f62w](url).
> 
> This issue was resolved on the version 2013.10.2. I then used the version of 2024.2.0 which also worked and then proceeded to update it to the latest version 2024.4.2

@excaliburzarau: Same issue for me and your solution helped!

**Comment by srkoster** [comment]
I'm facing the same error message. I went from 2024.2.1 to 2024.2.2 to 2024.2.3 and now to 2024.4.2 where the error occurs. Running on Kubernetes K3S 1.26.10 with an Postgresl 16.1 database (cloudnative-pg).

**Comment by excaliburzarau** [comment]
> I'm facing the same error message. I went from 2024.2.1 to 2024.2.2 to 2024.2.3 and now to 2024.4.2 where the error occurs. Running on Kubernetes K3S 1.26.10 with an Postgresl 16.1 database (cloudnative-pg).

Hello,

What actually worked for me was the progressive upgrade. I would suggest to start on the 2023.1.1 and then use the 2023.8.1 (which has a login bug when the login is bypasses). This has to BE done because it seems that you can not go directly to the 2023.10.2 but after that you can go to the 2024 Release. 
I cannot tell you for sure if it Will work for you but it did work for me every time .

Best Regards

**Comment by janosmiko** [comment]
We are facing the same issue. I tried to go through the list above, but that didn't help.

**Comment by excaliburzarau** [comment]
If this is a clean installation i would ensure that the volumes/mountpoints were empty. It did happened once on the Second time i tried it. Cheers
